### ISSUE TITLE
Media for Pages not importing

### ISSUE THREAD

**Issue by wdet30** [arsmentis/wdet-conversion#100]
Hey @artlogic @metastange, I was trying to import the pages and media for the shows and music pages including podcast pages. I have spent most of the day trying to resolve this. 

This is not urgent or a deal breaker. 

Solution:
This will require updating the show music series page banner and feature images after data imports.

I'm hoping to get help from @Jazzyhunt on this.

I will bring the solution to the Monday meeting.

**Comment by artlogic** [comment]
The media needs to come from somewhere. You need to have it hosted somewhere and update the domain/URLs in the XML files to match.

**Comment by wdet30** [comment]
We have a handle on this now.
