### ISSUE TITLE
Line added to functions ,PHP

### ISSUE THREAD

**Issue by wdet30** [arsmentis/wdet-conversion#101]
@artlogic, I have added code to functions .php on the dev site.  This allows for the pages to show the excerpt. How would you like this updated on Github? Should I upload the version I just edited? Let me know how to procced when I make a change to the Theme.

"add_post_type_support( 'page', 'excerpt' );"

**Comment by artlogic** [comment]
What's the difference between what's in github and the version you just edited? Just a single line?

**Comment by wdet30** [comment]
Yes

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by artlogic** [comment]
Add the line using any method you like.

**Comment by wdet30** [comment]
I wanted to make sure that it was backed up properly along with your changes.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by artlogic** [comment]
What exactly was backed up? GitHub?

**Comment by wdet30** [comment]
No I just added the line to the functions.php in the theme. Should I add it anywhere else? I'm not sure if you wanted me to add the line to the functions.php that's in GitHub. Let me know

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by artlogic** [comment]
If you are comfortable managing the theme on your own then I will remove it entirely from github.

**Comment by wdet30** [comment]
Nope, I'm sure you made a lot of changes that I don't have a hold of so I'm really just trying to get a hold of all the changes you made. I will need your help.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by artlogic** [comment]
You can review any changes I made here: https://github.com/arsmentis/wdet-conversion/commits/main/theme/tony-brown-news-pro-35/functions.php

**Comment by wdet30** [comment]
Copy

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
