### ISSUE TITLE
Excerpts on Pages (NOT POSTS.)

### ISSUE THREAD

**Issue by metastange** [arsmentis/wdet-conversion#102]
"Excerpts" (in this case, program descriptions) are NOT showing up on the show, podcast or series landing pages, but they ARE displayed on the individual show, podcast and series pages. Screenshots and links below.

Landing page example: https://wdetcms.wdet.org/shows/
![Screen Shot 2022-01-05 at 12 57 05 PM](https://user-images.githubusercontent.com/85897115/148265973-3963ec3b-6285-4b8c-866e-7a837e182825.png)

Individual show page example: https://wdetcms.wdet.org/shows/1a-jenn-white/
![Screen Shot 2022-01-05 at 12 58 00 PM](https://user-images.githubusercontent.com/85897115/148266018-975c207e-8389-4032-a1ce-eac4f16819fc.png)

**Comment by wdet30** [comment]
@metastange , I think I resolved it. Please verify and close if we are good.

https://wdetcms.wdet.org/shows/1a-jenn-white/

**Comment by metastange** [comment]
I'm seeing the excerpts on the landing page, which is good, but it's also still showing up on the individual pages, which it shouldn't be.

<img width="884" alt="Screen Shot 2022-01-05 at 3 15 48 PM" src="https://user-images.githubusercontent.com/85897115/148283066-ba377f67-fb39-4d27-b3b7-200913c81bc4.png">

**Comment by wdet30** [comment]
Sorry. I neEd to dig deeper. TB

**Comment by wdet30** [comment]
@metastange , still working on this. Hello @artlogic is this something we can do since your are calling the excerpt back into the post? Even when I add the "add_post_type_support( 'page', 'excerpt' );" I can't control the excerpt from back into the page. Any idea or help ?

**Comment by wdet30** [comment]
@metastange , I have looked around. I'm not sure if we can hide the excerpt on pages and not post. I will wait to hear back from @artlogic on this. I just exhausted my search for a fix.

**Comment by artlogic** [comment]
I want to clarify a few points here:
1. We want excerpts on posts - we aren't trying to hide those.
2. We don't want excerpts on pages.
3. We do want to see excerpts on the category lists that include pages.

So it looks like we just want to remove the excerpts from the pages - correct?

**Comment by wdet30** [comment]
@artlogic Yes sir.

**Comment by artlogic** [comment]
What put the excerpts there in the first place?

**Comment by wdet30** [comment]
It seems that she's trying to use that to put the program data and do a blog post for preview in the blog view. I had to hard code function.php for the excerpt field just to go to pages. I'm hoping there will be a workaround is there a way we can just keep things the way they are for pages? And excerpts. Can you please explain to James how you want to use them a little bit more. Thanks @Meta ***@***.***>


________________________________

**Comment by artlogic** [comment]
What code or configuration caused the excerpts to start appearing on the pages?

**Comment by wdet30** [comment]
It's in function.php  add_post_type_support( 'page', 'excerpt' ); @artlogic 

Thanks

**Comment by artlogic** [comment]
What happens if that's removed?

**Comment by wdet30** [comment]
Then the excerpt field does not show up in pages.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by artlogic** [comment]
In the admin, on the site, or both?

**Comment by artlogic** [comment]
@metastange this should be resolved - can you please verify

**Comment by metastange** [comment]
@artlogic - yes, looks correct on my end. is the update documented elsewhere, am i good to close this issue?

**Comment by artlogic** [comment]
The linked commit (https://github.com/arsmentis/wdet-conversion/commit/ed89e0bd75160e895a7bfcfc8cc97aa231aa5d19) should be all the documentation needed - assuming @wdet30 creating the theme zip file from github.
