### ISSUE TITLE
Access to Redirects

### ISSUE THREAD

**Issue by metastange** [arsmentis/wdet-conversion#105]
@wdet30 @artlogic I am trying to verify some redirects used on the old site (ie wdet.org/artist pointing to artist next door series) and do not appear to be able to access redirects with my user account; can you enable me to do so or point me in the right direction? I might just be missing it.

**Comment by artlogic** [comment]
Can you access it here?

https://archive.wdet.org/admin/redirects/redirect/

**Comment by artlogic** [comment]
Oh, wait - were you talking about redirects on the new site?

Those are plugin settings and likely can only be accessed by administrators. For the time being I'm going to elevate your access. I think we're going to need to have a longer discussion about this soon.

**Comment by artlogic** [comment]
You should now be an admin.

**Comment by wdet30** [comment]
Meta permissions updated.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dorothyhernandez** [comment]
@artlogic Can you clarify what I'm looking for author redirects? We're seeing categories and old site redirects under redirection but not sure what I'm supposed to checking for author profiles.
