### ISSUE TITLE
Styling issue - mobile nav

### ISSUE THREAD

**Issue by metastange** [arsmentis/wdet-conversion#106]
Mobile nav needs to be cleaned up, ideally to match the old version, but if that's not feasible, at least remove the large blue bar and drop the search into the hamburger menu.

current:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/85897115/148792236-9894e6bd-2386-4f8e-8abd-d91140e782ae.png)

old version:
![IMG_F69AB9946FAB-1](https://user-images.githubusercontent.com/85897115/148792334-35d3f5fa-7e7e-437c-8129-4861e73499c1.jpeg)

**Comment by artlogic** [comment]
Removing myself for now - let me know if you need a hand @wdet30.
