### ISSUE TITLE
Adding Users/Authors - Editor Permissions Issue

### ISSUE THREAD

**Issue by metastange** [arsmentis/wdet-conversion#108]
It appears that with editor access, I am unable to add new users (or even access user data). Sam Corey (sam.corey@wdet.org) is a new employee who needs an author profile.

**Comment by artlogic** [comment]
I will add in Sam. We need to sort out permissions at the meeting this afternoon.

**Comment by metastange** [comment]
Thanks, @artlogic! I'll make some notes on permissions to discuss later.

**Comment by metastange** [comment]
what's sam's username?

**Comment by artlogic** [comment]
He can just login with his email. He should have actually received an email from wordpress.

**Comment by metastange** [comment]
all set, can you update him to an editor (for now)? He needs to be able to edit a post he did not start. 

Adding this to my permissions list questions!

**Comment by artlogic** [comment]
Done.

**Comment by metastange** [comment]
admins:
- Tony
- Dorothy

editors:
- Matt Trevethan
- Sam Corey
- Jake Neher
- Ryan Patrick Hooper
- Amanda LeClaire
- LaToya Cross
- Detroit Today intern (maybe DT Intern?)

Is it possible to keep my account as admin until friday before i no longer access it? I need to clean up some redirects and author data.

**Comment by artlogic** [comment]
This has been taken care of. There are a few outstanding issues:

1. tbrown needs to be demoted to editor or author.
2. We need to make a tbrown_admin ID
3. I'm not sure what the deal is with the wdetdigital admin, but it likely should be removed.
4. Meta's ID will remain an admin for the next 4 days until it's removed.

That should be everything!

**Comment by wdet30** [comment]
Do not remove remove my permissions. They are connected to the theme license

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by wdet30** [comment]
I will deal with permissions don't edit WDET digital as well

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by artlogic** [comment]
We're waiting for you. That's why they're outstanding. Get some rest.

**Comment by wdet30** [comment]
Copy that

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by artlogic** [comment]
@wdet30 

I'd like to get this sorted out:

    1. tbrown needs to be demoted to editor or author. (or renamed to tbrown_admin)
    2. We need to make a tbrown_admin ID, or a tbrown ID if the above is renamed.
    3. I'm not sure what the deal is with the wdetdigital admin, can you explain?

Let me know what you're thinking here.

**Comment by wdet30** [comment]
Hey I'm looping in Ryan in the email chain we met on this yesterday. Can we please circle back to you tomorrow on this we do have a solution. I'll start demoting accounts and getting all that stuff done tomorrow.

TB

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by wdet30** [comment]
Absolutely correct, we are taking your advice. I just need to change the email address on a few license plugins. And I was going to do that tomorrow.

T

________________________________

**Comment by artlogic** [comment]
Closing in favor of #111 and fixing the admin accounts.
