### ISSUE TITLE
Options for fine grained permissions in wordpress

### ISSUE THREAD

**Issue by artlogic** [arsmentis/wdet-conversion#111]
Here are some (of I'm sure many) options to give WordPress a permissions system, like Django or Drupal:

https://www.ostraining.com/blog/wordpress/best-permissions-plugins/

**Comment by dorothyhernandez** [comment]
@artlogic Is there a way to add Elementor editing capabilities under my Editor account vs admin? I will need to use that function with every post and from what I understand I should only be logging into my admin account for admin tasks.

**Comment by wdet30** [comment]
Yes I can grant editors access to elementor. Do you need it today? Please advise @Dorothy ***@***.***>

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dorothyhernandez** [comment]
@wdet30 I don't need it today just whenever you get to it. Thanks.

**Comment by wdet30** [comment]
I wil go over tickets first thing tomorrow.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by artlogic** [comment]
I believe the issues went beyond Elementor. For instance, there's no way to restrict who can publish articles. There's also no way to grant people access to customizer or redirects without them being an admin (unless you know of a way I'm not).

**Comment by wdet30** [comment]
No way only admins can manage plugins.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by artlogic** [comment]
> No way only admins can manage plugins.

I figured as much but several of the plugins listed allow you to manage things like who can publish, who can create certain content types, etc...

**Comment by wdet30** [comment]
Yep, we'll chat about that and me you and Ryan and maybe even Martin have a conversation if we really want to use those plugins. I'm game if your game.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by artlogic** [comment]
Closing until needed.
