### ISSUE TITLE
Remove automatic wdet.org category tag on all posts

### ISSUE THREAD

**Issue by dorothyhernandez** [arsmentis/wdet-conversion#113]
We didn't notice it before but there appears to be a wdet.org category tag that's being automatically applied to all new web posts. For the time being I'm just unchecking them all but it would be more efficient to have it taken off.

**Comment by wdet30** [comment]
Hey @dorothyhernandez, this is the fallback for post without a category. What should we name it? It can't be deleted. If someone does not check a category a post will fall to this category by default. What should the name be? Please advise. "News" "wdet something"?
![screen1](https://user-images.githubusercontent.com/84190532/149221334-68420956-5ad9-456a-a723-62fa22451e98.png)

**Comment by artlogic** [comment]
https://wdet.org/wp-admin/edit.php?category_name=wdet-org
