### ISSUE TITLE
Permalinks changing after posts are updated

### ISSUE THREAD

**Issue by dorothyhernandez** [arsmentis/wdet-conversion#114]
@wdet30 @artlogic Whenever I change the permalinks to something more reader friendly, after I hit save after making the change it goes to a string of numbers and revision1 e.g. https://wdet.org/2022/01/12/123740-revision-v1/.

What I change it to manually
<img width="822" alt="Screen Shot 2022-01-13 at 1 01 17 PM" src="https://user-images.githubusercontent.com/91985309/149384326-7da7c136-92ef-4faa-88aa-f55f6ddf4364.png">

What the system changes it to after I hit save/update:
<img width="818" alt="Screen Shot 2022-01-13 at 11 50 48 AM" src="https://user-images.githubusercontent.com/91985309/149413247-b300d306-7d5d-4655-8b6e-ff1fbd6cbf98.png">

I think it has something to do with my admin account because when Meta does a change to a post that's been published the "revision1" link doesn't occur.

In my admin account I also cannot access Authors. No dropdown field shows up.

<img width="248" alt="Screen Shot 2022-01-13 at 4 42 22 PM" src="https://user-images.githubusercontent.com/91985309/149413486-82a4091a-6197-4087-af22-a95ea3663a6e.png">

**Comment by dorothyhernandez** [comment]
Per the Web Launch Status meeting on 01.24.22, flagging this as one of the top priorities since I have been avoiding using my admin account because I don't want to further mess up links but that means I can't use Elementor.

**Comment by artlogic** [comment]
@dorothyhernandez can we schedule a meeting tomorrow sometime so we can do a screen share and attempt to get this resolved?

**Comment by dorothyhernandez** [comment]
@artlogic I'm trying to replicate it but now the permalinks are not changing. Not sure how it happened before (it happened a handful of times) but I can't do it again. I guess I'll close this for now and then reopen if it happens again.

**Comment by artlogic** [comment]
Sounds good - lmk if it happens again!
