### ISSUE TITLE
Optimize website for mobile devices

### ISSUE THREAD

**Issue by dorothyhernandez** [arsmentis/wdet-conversion#116]
Clean up formatting of website on mobile devices. 

Current issues:
- Nav bar doesn't have "shows, podcasts, series" etc.
- Banner ad cut off
- Probably don't need "recent" section because the same posts are repeated below so it might seem redundant, maybe just a "latest" section and all of the recent posts show up 
- 
<img width="345" alt="Screen Shot 2022-01-19 at 11 27 44 AM" src="https://user-images.githubusercontent.com/91985309/150172937-517cb0d0-6dda-423c-843a-3064d2f18760.png">

<img width="342" alt="Screen Shot 2022-01-19 at 11 28 03 AM" src="https://user-images.githubusercontent.com/91985309/150173011-037a8b08-793f-4e03-a3d2-e59246a06b73.png">

**Comment by dorothyhernandez** [comment]
Got another comment on mobile formatting so I'll add them here as I get them.

From Eli Newman: 
The first thing that stands out is that there is no easy access to a “listen“ button for the stream. And there is some strange formatting that occurs with ads and article, mainly cutting off headlines. You can also scroll to the right where it’s blank.

<img width="302" alt="Screen Shot 2022-01-19 at 2 31 43 PM" src="https://user-images.githubusercontent.com/91985309/150200957-eeadd183-3367-470d-b93d-c69b8421b52a.png">

**Comment by artlogic** [comment]
There's a lot of overlap here with #119 and #118 - I think we need to sort these issues out into individual issues - would that be something that either @dorothyhernandez or @dmsanderswdet can do?

I'm happy to do it, but I assume you would want to be paying me to do more technical work.

**Comment by dorothyhernandez** [comment]
@artlogic I can break them out. So just to make sure I am doing this in the most efficient way and to streamline these issues, create a separate issue each for:
1) Listen button on mobile
2) Banner ad cut off on mobile
3) HMTL code from photos being pulled into copy on mobile
4) Headlines cut off on the front page on mobile

**Comment by artlogic** [comment]
Yes - that's perfect - we've already got #118 for the listen button (which has a workaround in place but doesn't strike me as fixed exactly).

Could you also break out #119 while you're at it - then you can tag these issues in the child issues and close the parents.

Thank you!

**Comment by dorothyhernandez** [comment]
@artlogic Got it, will clean this up.

**Comment by dorothyhernandez** [comment]
Closing this to break out into individual issues.
