### ISSUE TITLE
Mobile Issues

### ISSUE THREAD

**Issue by dmsanderswdet** [arsmentis/wdet-conversion#119]
I'm concerned that this website was launched too quickly without concern for our listeners or website users. It's not utilized for mobile at all -- you can't even stream the station from the mobile website because it removes the play icon (this is the main reason people come to our website). This is 2022 -- everything is about mobile interface. It may have marginally improved the backend, but there's so many weird spacing issues and glitches -- pulling HTML code from photos into the description, the cut off of headlines on the front page (why would you click any of those boxes if you can't even read the headline?), the random added hyphen to every headline. I really wish the original website would've stayed up while this one got the kinks worked out. It's not very motivating to even want to share any content from the website with listeners or friends because it feels so behind the times. I hope these issues can be worked out.

**Comment by artlogic** [comment]
This needs to be broken out into multiple issues - one for each point brought up. We also need to follow-up with the person who submitted this for more clarity.

**Comment by artlogic** [comment]
This listen button is already documented in issue #118. The other issues need to be broken up and followed up on.

**Comment by dorothyhernandez** [comment]
Closing this to break out into individual issues.
