### ISSUE TITLE
AudioFile Upload Error

### ISSUE THREAD

**Issue by dmsanderswdet** [arsmentis/wdet-conversion#120]
error message while trying to upload an audio file into wordpress. I tried uploading it multiple times and checked if it appeared and it did not. (Laura Herberg)

**Comment by artlogic** [comment]
I need the associated screenshot - we're still waiting on Laura to get back to us, but I cannot access it.

**Comment by artlogic** [comment]
Received more info from Laura:

> So I was weirdly able to upload the audio using the "feature audio" feature, but I wasn't able to upload the audio by trying to do so in text. But I guess after I successfully managed to upload it using the Feature audio feature our digital manager was able to then input it into the text. That said, I'm worried that I might run into the problem again if I just wanted to upload audio in text but didn't want it to be featured.

I've asked for clarification and a step by step reproduction.

**Comment by artlogic** [comment]
No updates on this issue over the past 30 days - is this still happening? Should this be closed, or moved to a different milestone?
