### ISSUE TITLE
Headlines and excerpts not showing up in Google search

### ISSUE THREAD

**Issue by dorothyhernandez** [arsmentis/wdet-conversion#121]
I was doing a Google search for something else and this showed up: the headline and excerpt are not optimized (the headline says "WDET 101.9FM WDET is Detroit's Public Radio Station" instead of the actual headline, which is "Pandemic Reveals Issues Already Prevalent for Older Adults Such as Loneliness, Holistic Health Care." The the excerpt is a jumbled mash of the headline and excerpt.

<img width="656" alt="Screen Shot 2022-01-26 at 1 53 07 PM" src="https://user-images.githubusercontent.com/91985309/151227823-842e1c42-2739-4986-99f4-1904331298e0.png">

**Comment by artlogic** [comment]
This is a theme issue - hopefully @wdet30 is close on the new theme.

**Comment by wdet30** [comment]
Here is my search result
![search1](https://user-images.githubusercontent.com/84190532/151402109-15a2077e-bc1d-4da7-9617-2de470136867.png)
.

**Comment by dorothyhernandez** [comment]
This is what I see when I Google "State of the State Michigan" and click on "News" (vs "All")

<img width="682" alt="Screen Shot 2022-01-27 at 11 48 02 AM" src="https://user-images.githubusercontent.com/91985309/151404814-2a4d4867-b346-42f1-aed7-ae96b1e75a95.png">

In some instances it's not pulling in the Excerpt but rather content that's in the body.

**Comment by wdet30** [comment]
Resolved from 1 day ago. 
![screen2581](https://user-images.githubusercontent.com/84190532/151752857-04535394-3b0c-4f6f-a974-a160e845f47f.png)
