### ISSUE TITLE
Mobile issues: Headlines at top of the front page

### ISSUE THREAD

**Issue by dorothyhernandez** [arsmentis/wdet-conversion#123]
Per survey feedback submitted on 01.25.2022. Headlines are cut off or are too long and cover the entire image. See below for example.

![WDET 101 9FM -](https://user-images.githubusercontent.com/91985309/151275155-080c7de9-1af9-4edf-a60d-c1295dd2a4ae.png)
.

**Comment by wdet30** [comment]
Resolved 
![Screenshot_20220131-020922](https://user-images.githubusercontent.com/84190532/151752552-e7503889-7c83-498a-9bb6-623a2b8595c5.png)
d
