### ISSUE TITLE
Mobile issues: Banner ad cut off

### ISSUE THREAD

**Issue by dorothyhernandez** [arsmentis/wdet-conversion#125]
<img width="342" alt="150173011-037a8b08-793f-4e03-a3d2-e59246a06b73" src="https://user-images.githubusercontent.com/91985309/151276992-016b2b8a-94e4-49b5-8996-2e03cef55311.png">

**Comment by wdet30** [comment]
![Screenshot_20220125-172234](https://user-images.githubusercontent.com/84190532/151389546-79d184ac-d9c6-4d5d-aefa-07f93fb427c2.png)

Here is the latest this has been resolved.
