### ISSUE TITLE
Center styling did not transfer

### ISSUE THREAD

**Issue by metastange** [arsmentis/wdet-conversion#13]
Podcast subscribe call to action is hard coded to center-align. It is populating left-aligned.

Examples:
https://layout.wdet.org/2021/07/16/ida-mae-brings-british-americana-across-the-pond/
https://layout.wdet.org/2021/06/02/science-of-grief-exploring-unexpected-loss/

**Comment by wdet30** [comment]
This is resolved. If you find this issues again please create new ticket with example links.
