### ISSUE TITLE
Update Jobs Page

### ISSUE THREAD

**Issue by dmsanderswdet** [arsmentis/wdet-conversion#130]
Per Tony's email.

**Comment by artlogic** [comment]
@wdet30 can you clarify?

**Comment by artlogic** [comment]
Fixed per @wdet30

**Comment by dmsanderswdet** [comment]
James,

The positions are appearing twice.  Tony and I are working on it.


Diane



Listen Live at  wdet.org<http://www.wdet.org/> or in the WDET mobile app<https://wdet.org/mobile/>

[cid:5088abf5-2547-42cb-878c-f043261c9670]

________________________________
