### ISSUE TITLE
Hamburger button not working on mobile

### ISSUE THREAD

**Issue by dorothyhernandez** [arsmentis/wdet-conversion#131]
Per feedback received 02.03.22 from WDET reporter and producer Eli Newman: "the three line button (I presume a dropdown menu) is not functioning on mobile."

I just tested it out and indeed when you tap on it, nothing happens.

![WDET 101 9FM » Watch Live President Biden delivers remarks on a U S  military raid that killed ISIS leader](https://user-images.githubusercontent.com/91985309/152374353-3f9c1d0e-504c-4492-afa4-7e2f24a17e86.png)

**Comment by artlogic** [comment]
waiting to hear back from @dorothyhernandez

**Comment by dorothyhernandez** [comment]
Thank you to our designer (who is apparently a web developer!!!!) Nikki Roach, we have figured out the problem. I followed up with Eli on the hamburger button functionality and he said it still wasn't working. He also has an iPhone. But then Nikki told me you have to tap to the right of the hamburger button and then it works.

From Nikki: Essentially, tapping the hamburger and exit button is not expanding/collapsing the menu, at least for me, when I tap that icon. I use Safari on an iPhone.

There is a screenshot of the menu as I see it on my phone. 

<img width="330" alt="Screen Shot 2022-02-09 at 12 43 40 PM" src="https://user-images.githubusercontent.com/91985309/153262827-270045a4-9929-462f-a29e-eb37d4bfe077.png">

And another of my browser inspect tool. 

![Image](https://user-images.githubusercontent.com/91985309/153262877-64ad721e-cd37-43ee-8571-453adde7d037.jpeg)

In the code version, I'm highlighting where the button is in HTML. Doing that highlights on my phone, where that button is on my page. I circled it in the screenshot - the button's active area. It's not where the icon is. Hence why, when I tap in the space to the right of the icon, I hit the active area and the menu does work.

**Comment by artlogic** [comment]
I can confirm I'm seeing this on some (not all) Apple devices. I'll look into it further.

**Comment by codingforapps** [comment]
This is an issue with the Safari browser. The **margin-left: auto;** on the icon is ignored by other browsers but safari uses it to apply a - (negative) left margin, moving the icon. This snippet was added to the CSS on the dev site and it solved the problem. 

```
.header-layout-2 .main-navigation i.ham{
	margin-left: unset;
}
```

**Comment by artlogic** [comment]
How was it added?

**Comment by codingforapps** [comment]
Into the massive CSS in the customizer... which is massive and idk how it's organized. 
Would you prefer it be added into the styles.css of the child theme? That is small its like 22 lines.

**Comment by artlogic** [comment]
I just needed to know how it was done so I can apply it consistently to production. I think cleaning up the customizer is probably a future task.

**Comment by artlogic** [comment]
Should be resolved - can you please test this in production @codingforapps and @dorothyhernandez? Thanks.

**Comment by dorothyhernandez** [comment]
It's working on my iPhone on Safari and Chrome.

**Comment by artlogic** [comment]
I think we're good.
