### ISSUE TITLE
missing icons on "featured" carousel

### ISSUE THREAD

**Issue by codingforapps** [arsmentis/wdet-conversion#138]
With the CoverNews theme, there are < > buttons intended above the featured section. 

<img width="438" alt="Screen Shot 2022-02-25 at 2 46 10 PM" src="https://user-images.githubusercontent.com/6656745/155785244-23986152-e7b5-417f-8955-9c770581a2c6.png">

I noticed this because in Firefox, I'm seeing "k" "o" because font-awesome cannot insert < > icons. 

<img width="627" alt="Screen Shot 2022-02-21 at 3 49 37 AM" src="https://user-images.githubusercontent.com/6656745/155785219-9438a550-7feb-4ab1-900e-58c09cb41cc8.png">

In Safari, I have no visible error, but the buttons are still there. They're clickable and move stories through the carousel.  

Even though font-awesome is loaded on our site four times...it's being overwritten by Fontello, a different icon font.

The easiest fix is to update CSS content properties so they have the right reference that Fontello uses.

```
.fa-angle-left::before{
content: "\e1019;" //left arrow
}
.fa-angle-right::before{
content: "\e1111;" //right arrow
}
```

**Comment by codingforapps** [comment]
supposedly that was the fix, but the font-awesome CSS overwrites it. normally i would avoid important declarations, but that worked well, there are < > icons now.
```

.fa-angle-left::before{
content: "\e1019" !important;
}
.fa-angle-right::before{
content: "\e1111" !important;
}
```

let me know if we think they are too small.

**Comment by artlogic** [comment]
@dorothyhernandez can you check this on dev and verify this looks OK to you?

**Comment by dorothyhernandez** [comment]
This looks good.

**Comment by artlogic** [comment]
@codingforapps can you update this file with the changes you made? https://github.com/arsmentis/wdet-conversion/blob/main/theme/Additional%20CSS.css

Thanks!

**Comment by codingforapps** [comment]
@artlogic that is done.

**Comment by artlogic** [comment]
Production updated.
