### ISSUE TITLE
Style & Layout

### ISSUE THREAD

**Issue by metastange** [arsmentis/wdet-conversion#14]
Currently, all content being pulled in with H3 styling is being converted to a weird font. Update H3 font on layout site.

**Comment by wdet30** [comment]
Fonts, will be updated this week in the final versions of the CSS.

**Comment by wdet30** [comment]
@wdet30 , I'm moving styling to this thread here.

**Comment by metastange** [comment]
Here are my additional styling notes. Let me know if you need these in some other format:

- [ ] Correct fonts
- [ ] Hover state for the WDET logo is weird (switches between two colors)
- [ ] Donate button should all be the same pink color (heart and "donate" currently a different font
- [ ] Missing Search from the top navigation
- [ ] Center align the navigation (currently slightly right of center)
- [ ] Do you think we need "home" in the nav? I'm ok with it, but also think clicking the logo is pretty intuitive
- [ ] Order of the nav (from left to right) should be Home, Shows, Podcasts, Series, Events, Schedule, Connect, Support Us
- [ ] Remove "Listen" (player is right above the nav)
- [ ] Shows, Podcasts and Series should have drop down menues
- [ ] Breaking news: Possible to customize this? Would prefer "Most Recent" or something like that and to change the color of the box
- [ ] Update mailchimp opt-in in sidebar
- [ ] Are the ad sizes different? I'm looking at a 970 x 250 that's cut off on the right margin
- [ ] Remove "Advertisement 2" text
- [ ] Center align advertisement 2
- [ ] Remove page scroller (currently showing through page 1,212) - possible to just make this "view more"?
- [ ] Remove "Donate! Support Detroit's NPR Station" from the bottom of pages
- [ ] Footer: All logos and text should be white
- [ ] Footer: Move "Schedule" and "Contests & Giveaways" up closer to the "Shows and Podcasts" section
- [ ] Footer: Add "FCC Applications"

**Comment by wdet30** [comment]
@metastange, above is the styling changes I'm working off of. If there any other CSS or styling issues please update them on this ticket #14

**Comment by metastange** [comment]
@wdet30 screenshotted examples of "Shows, Podcasts and Series should have drop down menu
![Screen Shot 2021-11-04 at 11 11 57 AM](https://user-images.githubusercontent.com/85897115/140342685-eb228638-7dc5-4ab5-a891-3904e2356dcb.png)
![Screen Shot 2021-11-04 at 11 11 43 AM](https://user-images.githubusercontent.com/85897115/140342698-53bc691e-a8b7-475f-96d3-678b3937302c.png)
s"

**Comment by wdet30** [comment]
Ahh, nav drop down menu for pages. Got it!

**Comment by metastange** [comment]
it might be space-prohibitive to list every show we have, so let me know if you want me to provide specific lists of what i'm looking for.

**Comment by wdet30** [comment]
I don't see that on the WDET.org

**Comment by wdet30** [comment]
Is this something new?

**Comment by metastange** [comment]
It's not on the current site - this was an improvement we discussed early when I was looped in

**Comment by wdet30** [comment]
Ok please provide list. Lets see how it looks.

**Comment by wdet30** [comment]
@metastange: Stylistically, not loving the shadowing on the boxes; it makes the pages look disconnected.
Please give screen of boxes.

**Comment by metastange** [comment]
Should I do that here or on issue #30 where that issue is listed? This is in reference to sidebars.

**Comment by wdet30** [comment]
Please list here @metastange

**Comment by wdet30** [comment]
@metastange, if it's styling list it here.

**Comment by metastange** [comment]
It's a little hard for me to give feedback on this because that note was made in reference to the links provided to review on CMS, which looks different from layout.

CMS (the "shadowing" I was referring to):
![Screen Shot 2021-11-04 at 3 37 20 PM](https://user-images.githubusercontent.com/85897115/140408545-22bfa6a7-76d6-445c-bf57-4ae1c68d1bec.png)

Layout
![Screen Shot 2021-11-04 at 3 37 38 PM](https://user-images.githubusercontent.com/85897115/140408580-a2c12e59-77f5-41d5-9a52-1d6416a1978a.png)
b

**Comment by wdet30** [comment]
H












Ok, yes I will note that.

**Comment by wdet30** [comment]
Got it, support sidebar! Noted as remove white box on support sidebar. In que

**Comment by metastange** [comment]
This was an issue across all sidebars, not just support, but I just wanted to prvide an apples to apples comparison

**Comment by wdet30** [comment]
So you want another color besides white behind the sidebar?

**Comment by wdet30** [comment]
@metastange, here is the latest update where we are on styling and CSS. I will have more for you when we meet on Friday.  

Pleased see the CSS Tab for updates on #14 #30 [Link to DOC](https://docs.google.com/spreadsheets/d/1Mn3GE9EvKJ2Mokv0kmrI4HsnmTZu_zTXYrq8uK150sw/edit#gid=116921514)

**Comment by metastange** [comment]
Yes, ideally, I would like it to be as similarly styled to the current site as possible.

Screenshot below and here's the hex: #dedede

![Screen Shot 2021-11-04 at 3 50 39 PM](https://user-images.githubusercontent.com/85897115/140410627-d054c1fd-09ec-49f0-9df4-95e5f4f6f07a.png)

**Comment by wdet30** [comment]
That's going to be tuff to pull off.  I will get back to you on this.


________________________________

**Comment by metastange** [comment]
> @metastange, So you want another color besides white behind the sidebar?

Did I misunderstand this question? I don't think I understand what information you're looking for. Let's add this to the agenda for tomorrow, please.

**Comment by metastange** [comment]
> Ok please provide list. Lets see how it looks.

**Shows**
- Detroit Today
- CultureShift
- Ann Delisi's Essential Music
- Don Was Motor City Playlist
- Modern Music
- The Progressive Underground
- This Island Earth
- All Things Considered
- Morning Edition
- View all shows

**Podcasts**
- MichMash
- CuriosiD
- Ann Delisi's Essential Cooking
- Science of Grief
- View all podcasts

**Comment by wdet30** [comment]
@metastange, I'm moving the request for Dropdown Menu on Navigation #65 feature request

**Comment by metastange** [comment]
- [ ] Add SEARCH to Nav

**Comment by metastange** [comment]
Re-upping the checklist above, removing what has been resolved and noted in the google doc:
- [ ]  Fonts still not populating correctly for me
- [ ] Possible to make the "search" icon in the nav a different color? it doesn't look great the way it is
- [ ]  Donate button should all be the same pink color 
- [ ]  Update mailchimp opt-in in sidebar (opt-in copy and style should match what's currently on site (COPY: Stay connected to Detroit. Subscribe to receive WDET’s weekly newsletters: // remove first name field // aligne check boxes and newsletter names)

Addition footer styling notes in issue #3

**Comment by wdet30** [comment]
@metastange, Working on this on and offline. I hope to have this looking good by Saturday, at least what i can fix in this version.
