### ISSUE TITLE
two "click-to-top" graphics

### ISSUE THREAD

**Issue by codingforapps** [arsmentis/wdet-conversion#144]
<img width="700" alt="Screen Shot 2022-02-28 at 6 27 21 PM" src="https://user-images.githubusercontent.com/6656745/156231116-d24a41f8-9efb-45f5-8f5d-2ca8c66849dd.png">

In wdetdev I've deactivated the plugin "clip to top" and now there is only the blue one. 

This is fixed in dev. 

I cross-checked on mobile and other browsers too. 

FYI —This button would pry not be necessary if it were not for the "you may have missed" and "more stories" sections which make our pages longer than before... and very long on mobile. I'm going to bring that issue up later.

**Comment by artlogic** [comment]
@wdet30 can you confirm this looks good in dev, and then deactivate in production? Thanks!

**Comment by artlogic** [comment]
Fixed. Closing.
