### ISSUE TITLE
favicon update

### ISSUE THREAD

**Issue by codingforapps** [arsmentis/wdet-conversion#145]
I've updated the favicon in wdetdev to reflect the old one. 

Comparing it here (white) to the old one (green)
![Image](https://user-images.githubusercontent.com/6656745/156240861-104ae380-7233-4cf9-97bc-df273dd8cbcd.jpeg)
![Image2](https://user-images.githubusercontent.com/6656745/156240867-307debb8-68fb-4989-b917-c1f5c3e95e36.png)

here's my browser too lol
<img width="113" alt="Screen Shot 2022-03-01 at 3 10 27 PM" src="https://user-images.githubusercontent.com/6656745/156241376-5e320ead-c0d8-473c-b783-566b3e607635.png">

**Comment by artlogic** [comment]
@codingforapps please assign issues to someone (probably you) and add the to a milestone when making them. Can you explain how you made this change?

@dorothyhernandez can you verify this is ok to promote to prod?

**Comment by codingforapps** [comment]
@artlogic sure i can apply those labels when creating issues

changed in Customizer > Site Identity

there's a place in Elementor too for this, but the Customizer had content populated into it already, so I didn't experiment.

i can put the graphic here too.

**Comment by artlogic** [comment]
@wdet30 approved this - I will add to production

**Comment by artlogic** [comment]
Completed.
