### ISSUE TITLE
Update Current Theme - CoverNews Pro!

### ISSUE THREAD

**Issue by wdet30** [arsmentis/wdet-conversion#147]
I have entered the license key a few times on both servers and it's not taking the key.

CoverNews Pro!

We may need to switch to vanilla Wordpres for a couple of hours to resolve this issue. It may have to happen over the next night or so to resolve.

So far I found this and will update it over the next 36 hours.

https://freemius.com/help/documentation/wordpress-sdk/license-activation-issues/

**Comment by wdet30** [comment]
I was able to update the key on both. I would like to still switch to vanilla Wordpres to update the theme one night this week.

**Comment by artlogic** [comment]
Why is that needed?

**Comment by wdet30** [comment]
Can we go over this in our meeting tomorrow Friday? I think it's best you advise me on how we should move forward with updating the theme. Let me know thanks.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by artlogic** [comment]
We need to update to 2.6.1 (from 2.6.0) in prod. It's been done in dev, but it wasn't seamless. We'll need to schedule time to take a snapshot and then do this during off hours.

@wdet30 is going to check to make sure this isn't a security update and schedule time based on the priority.

**Comment by wdet30** [comment]
@artlogic , couldn't find any updated info on the latest patch. I will send an email to support for info.

**Comment by artlogic** [comment]
Done
