### ISSUE TITLE
Question - How are "related posts" determined

### ISSUE THREAD

**Issue by metastange** [arsmentis/wdet-conversion#15]
Screenshot of posts determined as "related content" to a post about [flood disaster declaration](https://layout.wdet.org/2021/07/15/biden-oks-disaster-declaration-after-detroit-area-flooding/). I know this isn't fully set up yet, but made me wonder how we determine what related content is pulled in. Tagging
![Screen Shot 2021-08-27 at 1 16 32 PM](https://user-images.githubusercontent.com/85897115/131165040-5f79dcdf-933d-4846-8347-9d490aa567f2.png)
?

**Comment by wdet30** [comment]
@metastange, here is the answer to this.

The Related Posts feature pulls relevant content from your blog to display at the bottom of your posts. It uses your post content, tags, and categories to automatically generate a list of relevant posts on your site.

https://wordpress.com/support/related-posts/
