### ISSUE TITLE
Hourly News upload - solution needed

### ISSUE THREAD

**Issue by wdet30** [arsmentis/wdet-conversion#21]
James, we will need to make a basic form that a user can upload a .mp4 to this path: 
"https://wdet.org/media/wdet/news_update.mp4" It was built into the current CMS. 

- [ ]  I will check for plugin, but an upload form will work as-well.

**Comment by artlogic** [comment]
Questions:
* Is there a reason why the path is important?
* Does the form need authentication?
* Could we just use the wordpress media upload?

**Comment by wdet30** [comment]
I'm looking into that now.

TB


________________________________

**Comment by wdet30** [comment]
We can move the location. It will need to be the same path and filename.mp4 every upload. 3x a day.

**Comment by artlogic** [comment]
If there was a way to edit the permalink for a media item it seems like that would do it - but I don't see a way. We might be able to do it with a redirect.

**Comment by wdet30** [comment]
Looing at updating a file. I will test.

**Comment by wdet30** [comment]
This will need to be an upload to an SFTP folder setup on the server. It does not need to to live in the WordPress directory.  Please setup a directory using path below. We will need to setup a user for this directory and get Pat and Team video on how to upload. This we need to loop in Ryan to make sure each user can get there laptop setup. 

WDET.org/newsupdates

Or can we do a upload form?

Please advise.

TB

**Comment by artlogic** [comment]
It's probably easiest to have this be done with an SFTP client if that's acceptable, rather than trying to create a standalone form. Let me know if that's going to be too much of a training issue.

**Comment by wdet30** [comment]
This works yes
SFTP client.




________________________________

**Comment by artlogic** [comment]
Please let me know if I need to do anything else here.

**Comment by wdet30** [comment]
Nothing, moving this to Ryan

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by artlogic** [comment]
Unassigning myself then.

**Comment by wdet30** [comment]
We have a solution for this.
