### ISSUE TITLE
Should users be mapped to authors (via the PublishPress Author plugin?)

### ISSUE THREAD

**Issue by artlogic** [arsmentis/wdet-conversion#22]
This is an extra step to the import and I need to know if users should be mapped to authors - if they are not, I don't believe I can do multi-author posts with that user. Please advise, and if so, should the user info be kept in the author profile, or the user profile?

**Comment by artlogic** [comment]
It looks like the authors plugin also completely overrides user profile data, so if you want wordpress generated profiles, users must be mapped.

**Comment by wdet30** [comment]
Going back to the reason we wanted the multi-user plug into a sign more than one user to a post. We are unable to do that with just the WordPress user setup. The best practice would be if we can map to both is that possible? If not then the preferred method would use the author plug-in. For the reason of assigning multiple authors to a post.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by artlogic** [comment]
I don't understand what you mean by map to both? Can you show me an example on wdetcms?

**Comment by wdet30** [comment]
Yes

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by artlogic** [comment]
Here's the outcome of this:

* For each person being pulled over, create a user and an author.
* Put profile information in both the user and author objects as it's not certain we'll stick with this plugin

**Comment by artlogic** [comment]
Closing for #20
