### ISSUE TITLE
Review Tag Import

### ISSUE THREAD

**Issue by artlogic** [arsmentis/wdet-conversion#23]
Please review the tag import and let me know if changes need to be made or if tags need to be cleaned up:

https://wdetcms.wdet.org/wp-admin/edit-tags.php?taxonomy=post_tag

Looks like we imported about 4000 tags from the old site.

@metastange you may need an ID to access the site - @wdet30 can help you with that, but you may lose access as more imports occur. Please work with me and @wdet30 to coordinate a site backup so your ID is maintained between imports.

**Comment by wdet30** [comment]
I was able to clean these up. We can manage these after launch. We will have to see if they are going to stick to the post when you bring them over. If not we will blow them out and start fresh with the Wordpress build.

T

**Comment by wdet30** [comment]
It seems so many tags was created in funky ways to prevent duplicates. Please don't import any unused tags if possible.  I think that would be the best way. Please advise. TB

**Comment by artlogic** [comment]
No problem - I can easily ignore inactive tags. Does anything else need to be done?

Keep in mind that if you remove/merge tags on the existing CMS, you may end yup with 404s due to the missing tags. I can't automatically generate redirects for those.

**Comment by wdet30** [comment]
404 will be updated with search and main blog feed and menu links.

**Comment by metastange** [comment]
Tags were not imported for assets, so assets are not included in the "tagged items" on the new site.
Examples:
old: https://wdet.org/admin/taggit/tag/5106/
new: https://wdetcms.wdet.org/wp-admin/edit-tags.php?taxonomy=post_tag&post_type=post&s=%23detroit

old: https://wdet.org/admin/taggit/tag/3399/?_changelist_filters=p%3D1
new: https://wdetcms.wdet.org/wp-admin/edit-tags.php?taxonomy=post_tag&post_type=post&s=abortion

Otherwise, tagging looks good.

Still looking for clarification from @wdet30 on the above. Let me know if I should open a new "training" issue.

**Comment by metastange** [comment]
Also, will the theme we're using include the "description" field? (The little disclaimer on the backend says "The description is not prominent by default; however, some themes may show it.")

**Comment by wdet30** [comment]
Please shy away from non-standard fields etc.

TB
________________________________

**Comment by metastange** [comment]
What makes this a non-standard field? It's built-in to the CMS, I was just looking for clarification as to whether it would show up on the theme we selected. 

I also just tested it with #detroit and it appears that the description field DOES show up. This is good to know, as it's an opportunity to provide context to grouped content without creating a whole new series/show/topic.

Here's the backend and front end for reference:
https://wdetcms.wdet.org/wp-admin/term.php?taxonomy=post_tag&tag_ID=3724&post_type=post&wp_http_referer=%2Fwp-admin%2Fedit-tags.php%3Ftaxonomy%3Dpost_tag%26post_type%3Dpost%26s%3D%2523detroit

https://wdetcms.wdet.org/tag/detroit_2/
