### ISSUE TITLE
How to transition page sidebars

### ISSUE THREAD

**Issue by artlogic** [arsmentis/wdet-conversion#25]
Page sidebars are separate from the page content in the old CMS. How should be be handled in wordpress?

**Comment by wdet30** [comment]
I will get the sidebar today. No need to import.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by artlogic** [comment]
They're different for each page. Are you going to manually create each one? How do you want me to associate a particular sidebar with a page?

**Comment by artlogic** [comment]
Got it - I will ignore the existing sidebars.

**Comment by wdet30** [comment]
Update, creating custom sidebar for music and support pages.
