### ISSUE TITLE
Dealing with People / Staff Page

### ISSUE THREAD

**Issue by wdet30** [arsmentis/wdet-conversion#27]
We will manually move these over on a case by case bias after launch. This is more of a staff section which can be easily created by and editor.

Link to section in CMS
https://wdet.org/admin/wdet/person/

**Comment by artlogic** [comment]
Profiles will be created automatically by the authors plugin. I don't think there's anyway to turn this off, but I don't know the plugin well. Can you advise @wdet30?

**Comment by wdet30** [comment]
It's off now. I just created Tony News by email, and he came in as a guest author I'm ok with that. He didn't show up as a user.

Please, look at the options here and let me now if you think we should bring them over a different way?

https://wdetcms.wdet.org/wp-admin/admin.php?page=ppma-modules-settings

That's fine, we can manually add them as a user and connect them to the plugin.

Tony

________________________________

**Comment by artlogic** [comment]
Yes, but that person still automatically was given an author page: https://wdetcms.wdet.org/author/tony-news/

So I think, unless you can somehow turn these profiles off, we should probably use then. I'll be pulling over all the author data, so each author will have a page automatically generated. The choices are this:

1. Pull over authors and try to populate the profile as completely as possible.
2. Pull over only the bare minimum and let the rest be done manually.
3. Find some way to turn off the profiles in the plugin and handle it all manually.

**Comment by wdet30** [comment]
The question is where to pull them to Categories? Please advise if you can. T



________________________________

**Comment by artlogic** [comment]
I don't know that it's possible (with this plugin) to apply a category to an author. Are you looking for some way to list current staff vs. previous staff and guest authors?

**Comment by wdet30** [comment]
We can make a staff category and go that route. That would work. Staff can be different from authors and users and have both Yes.

Hopefully we won't be changing staff information much.
________________________________

**Comment by artlogic** [comment]
If make staff a category, then I think you'd have to manually make pages for each staff member, then make redirects to those pages from the automatically created author profiles. Is that what you're thinking?

**Comment by wdet30** [comment]
I have also seen stations use slightly styled WordPress site for staff and linked to it. That may be and idea.

________________________________

**Comment by artlogic** [comment]
I'm going to hold off on importing anything but the bare minimum for authors until this is determined. Please let me know what you decide.

**Comment by wdet30** [comment]
We did the same thing at Michigan Radio. WordPress site for staff and sponsorship department. I want to go that route for the staff pages. T

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by wdet30** [comment]
See here: https://sponsorship.michiganradio.org/


________________________________

**Comment by artlogic** [comment]
So I'm assuming you plan to setup redirects from the built in author profiles to this separate WordPress site? You'll handle all that manually after the import?

**Comment by wdet30** [comment]
Yes we can link to their employee page on the other site. What will we lose if we don't Import the people into the new WordPress site?

**Comment by artlogic** [comment]
I have to import authors, unless you don't want authors on posts. Maybe we should have a quick conversation about this?

**Comment by wdet30** [comment]
Authors are fine. I'm talking about the people section that hold our staff bio info etc. 

This section will go to another WP build for staff only.
https://wdet.org/admin/wdet/person/

I want to be clear that we don't need this section, and it's not tied to authors, post, and we won't lose any news content if we don't import them.

Please advise

**Comment by artlogic** [comment]
My theory is that the way we do this is by creating redirects that cause the author profile links that are linked to every article to instead go to the separate site. The other option would be to override the profile links somehow via a plugin (or maybe the authors plugin already does this?)

I think we would want to test this before we settle on using a secondary site.

**Comment by wdet30** [comment]
Let's try it. I'm down to test.  FYI,  they do want a second site for the staff page.


________________________________

**Comment by artlogic** [comment]
Are you able to override the profile links? That's the cleaner option.

**Comment by wdet30** [comment]
When you say profile, you're referring to the person as in the people listings? We can go in and turn those listings off and make them non-active. Is that the question? Yes we can make people inactive and turn your profile / person off first.


________________________________

**Comment by artlogic** [comment]
See the author section at the bottom of this article? https://layout.wdet.org/solving-mysteries-in-music-history-with-dso-librarian-robert-stiles-2/

That's the concern. How do you want to handle that?

**Comment by wdet30** [comment]
It looks like we can manually connect them to each author profiles manually.

**Comment by artlogic** [comment]
Still working on images (they're tricky to get right and represent a large chunk of the total work). I'll post another update around noon today.

**Comment by metastange** [comment]
@artlogic - i'm noticing issues with the author urls (for example, Alex Trajano's author url is ccampbell). Do you want me to document them here or manually change them myself? also at this point in the import process, should there be posts associated with the authors?

**Comment by wdet30** [comment]
The Staff page has been manually created until we come up with a long term solution. We will manually link to their author page on the CMS site. If they are not and Author or User we will create a "Staff" Category and list/post that staff member that way.

https://layout.wdet.org/wdet-staff/

We will link after we move pages to CMS site.

**Comment by metastange** [comment]
I've reviewed and cleaned up the staff page - i'd like to rebuild it to be a little more spiffy, but that can be done post-launch.

**Comment by wdet30** [comment]
Rebuilt on live site?
________________________________

**Comment by metastange** [comment]
Yes. Can go live as-is though, that's not a pressing project (and is just because I'm seeing all that Elementor can do so think we can make it look a lot nicer!)

**Comment by metastange** [comment]
The page itself is fine and I've made a note that this a post-launch improvement opportunity. Closing this ticket.
