### ISSUE TITLE
Events Page- Solution 

### ISSUE THREAD

**Issue by wdet30** [arsmentis/wdet-conversion#28]
There will be a plugin for events. Please don't create any pages or import data from events. These can be setup and running after launch and the site style.CSS is in a final version. 

It will take 1 hour to setup. TB

**Comment by artlogic** [comment]
OK - I just want to verify, my action item here is to do nothing? If so, I'll remove my assignment.

**Comment by wdet30** [comment]
Yes, thanks. T
________________________________

**Comment by wdet30** [comment]
All set @dmsanderswdet @dorothyhernandez @artlogic 

https://wdet.org/events/

Now live
