### ISSUE TITLE
Site Footer.

### ISSUE THREAD

**Issue by wdet30** [arsmentis/wdet-conversion#3]
<?php
/**
 * The template for displaying the header
 *
 * Displays all of the head element and everything upto navigation menu.
 *
 * @link https://developer.wordpress.org/themes/basics/template-files/#template-partials
 */
?>
<!DOCTYPE html>
<html>
     <head <?php language_attributes(); ?>>
          <meta charset="<?php bloginfo( 'charset' ); ?>">
          
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <meta http-equiv="X-UA-Compatible" content="ie=edge">
          <?php wp_head(); ?>
     </head>
      <body <?php body_class(); ?>>
        <?php
            if ( function_exists( 'wp_body_open' ) ) {
                wp_body_open();
            }
        ?>
        <a class="skip-link" href="#content">
        <?php esc_html_e( 'Skip to content', 'spark-news' ); ?></a>
            <div class="mobile-menu-overlay"></div>
            <?php get_template_part( 'template-parts/header/section', 'topbar' ); ?>
            <header class="site-header">
                <div class="container">
                     <div class="row vertical-align">
                          <div class="col-md-12 header-flat clearfix">
                                <div class="ct-branding">
                                    <?php get_template_part( 'template-parts/header/site', 'branding' ); ?>
                                    <nav class="site-navigation">
                                      <?php
                                        if ( has_nav_menu( 'header_menu' ) ) :

                                            wp_nav_menu( array(
                                                'theme_location' => 'header_menu',
                                                'container' => 'ul',
                                                'menu_class' => 'main-nav',
                                            ) );

                                        endif;
                                      ?>
                                    </nav>
                                </div>

                                <div class="ct-iconset ct-mobile-social clearfix">
                                     <div class="ct-social">
                                        <?php
                                          if ( has_nav_menu( 'social_menu' ) ) {
                                              wp_nav_menu(
                                                  array(
                                                      'theme_location'    => 'social_menu',
                                                      'container'         => 'li',
                                                      'menu_id'           => 'menu-social-items',
                                                      'menu_class'        => 'menu-items menu-social',
                                                      'depth'             => 1,
                                                      'link_before'       => '<span class="screen-reader-text">',
                                                      'link_after'        => '</span>',
                                                      'fallback_cb'       => '',
                                                  )
                                              );
                                          }
                                        ?>
                                     </div>
                                          <div class="ct-useful">
                                              <a href="#" class="js-search-icon"><span class="search-icon"><span class="icon icofont-search-2"></span></span></a>

                                              <div class="header-search-form clearfix">
                                                  <?php get_search_form( $echo = true ); ?>
                                                  <a href="#" id="close">
                                                      <span class="icofont-close-line"></span>
                                                  </a>
                                                  <p><?php echo esc_html__( 'Hit enter to search or ESC to close', 'spark-news' ); ?></p>
                                              </div>
                                              <span class="search-overlay"></span>

                                            <a href="#" class="js-mobile-close-icon mobile-close-icon"><span class="icofont-plus js-mobile-icon mobile-icon"></span></a>
                                          </div>
                                </div>
                          </div>
                     </div>
                </div>
            </header>
            <nav class="mobile-navigation">
              <?php
                if ( has_nav_menu( 'mobile_menu' ) ) :
                    wp_nav_menu( array(
                        'theme_location'    => 'mobile_menu',
                        'container'         => false,
                        'menu_class'        => 'main-nav',
                        'depth'             => '4',
                        'walker'            => new spark_news_Dropdown_Toggle_Walker_Nav_Menu()
                    ) );
                elseif ( has_nav_menu( 'header_menu' ) ) :
                    wp_nav_menu( array(
                        'theme_location' => 'header_menu',
                        'container'         => false,
                        'menu_class'        => 'main-nav',
                        'depth'             => '4',
                        'walker'            => new spark_news_Dropdown_Toggle_Walker_Nav_Menu()
                    ) );
                endif;
              ?>

              <div class="ct-iconset ct-mobile-social clearfix">
                <div class="ct-social">
                  <?php
                    if ( has_nav_menu( 'social_menu' ) ) {
                        wp_nav_menu(
                            array(
                                'theme_location'    => 'social_menu',
                                'container'         => 'li',
                                'menu_id'           => 'menu-social-items',
                                'menu_class'        => 'menu-items menu-social',
                                'depth'             => 1,
                                'link_before'       => '<span class="screen-reader-text">',
                                'link_after'        => '</span>',
                                'fallback_cb'       => '',
                            )
                        );
                    }
                  ?>
                </div>
                <a href="#" class="inside-mobile-close-button js-mobile-close-icon"><span class="icofont-plus js-mobile-icon mobile-icon"></span></a>
            </nav>

**Comment by artlogic** [comment]
This is just a test issue. Closing.

**Comment by wdet30** [comment]
I'm reopening this. I will need to redesign and style the footer. I'm getting to many errors in the transfer of the footer from the old site.
I'm redoing footer.php

**Comment by wdet30** [comment]
@metastange & @artlogic, I'm going to use the native WorPress footer. The footer PHP from the old site it becoming a major setback. 

This should be completed Thursday.

**Comment by artlogic** [comment]
I'm unassigning myself and untagging import issue as this doesn't have anything to do with me or the import process.

**Comment by wdet30** [comment]
Nope

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by metastange** [comment]
@wdet30 I did not get an assignment to review the footer - is it complete as-is on wdetcms? Is it possible to update it at all? I have some concerns about the look.

**Comment by wdet30** [comment]
Sure please list changes here.



________________________________

**Comment by metastange** [comment]
- [ ] Possible to change background color? I remember you mentioning something about it, but I can't find any details. If not, can we at least make the copyright text box the same color?
- [ ] WDET and NPR logos should be closer to the same size. Let me know if you want me to provide files.
- [ ] Scale down "Detroit's NPR Station, Your connection to news, music, conversation (currently getting a line break that separates a word)
- [ ] Reduce spacing between all footer items

**Comment by metastange** [comment]
Reopening this to address the checklist above.

**Comment by wdet30** [comment]
Rebuilding and fixing to your notes. Should be done 1/6/21 after 4pm for your look over. @metastange

**Comment by wdet30** [comment]
I'm not sure what to do about social icons. These are the ones provided by elementor.  They seem to link to the right pages. What can I do to resolve this? 

WDET and NPR logos please provide files you would like.

**Comment by metastange** [comment]
This is what I'm seeing on the social icons:
<img width="251" alt="Screen Shot 2022-01-06 at 11 39 05 AM" src="https://user-images.githubusercontent.com/85897115/148417610-7c339bb4-7677-4cdc-98c7-6e64f573f18b.png">

I used Elementor provided logos on the podcast page buttons and there was a fair amount of flexibility in formatting. At minimum, the social icons need to be centered in the colored boxes.

Re-sending the wdet and npr logos via email.

**Comment by wdet30** [comment]
@metastange , I was able to clean up the footer. One thing we are stuck with the ugly copyright call in the footer. This is calling from the theme general colors. I don't won't modify this until after launch and I get more control of the colors in the upgrade of the theme. Please give a look at the links logos and other items. TY

**Comment by metastange** [comment]
The same issue is happening with the social icons, but they're round now:
<img width="277" alt="Screen Shot 2022-01-06 at 1 00 08 PM" src="https://user-images.githubusercontent.com/85897115/148428926-57b7701a-5da1-4ee9-b58b-a3026e00f689.png">

Also, the logos I sent over were to size. If they're going to be scaled up (which they are on the updated footer), i can resend higher-res versions; the NPR one looks a little fuzzy.

Heard on the copyright issue.

**Comment by artlogic** [comment]
Non-vector images should be sized 3-4 times their display size to account for higher DPI displays. They will look fuzzy otherwise. Ideally use vector images if you can, which don't exhibit this problem.

**Comment by metastange** [comment]
Thanks @artlogic. @wdet30 I re-sent vector logos via email.

**Comment by wdet30** [comment]
@metastange, can you please give a look at the social icons and see if you can get them how you like?

Here is the edit link

https://wdetcms.wdet.org/wp-admin/post.php?post=120477&action=elementor
