### ISSUE TITLE
What to do about duplicate authors (people)

### ISSUE THREAD

**Issue by artlogic** [arsmentis/wdet-conversion#34]
We've got a small number of authors with duplicate names:

```
+----------+------------+------------+
| count(*) | given_name | surname    |
+----------+------------+------------+
|        2 | Nina       | Ignaczak   |
|        2 | Candice    | Fortman    |
|        2 | Tia        | Graham     |
|        2 | Eryka      | Cheatham   |
|        2 | Dorothy    | Hernandez  |
+----------+------------+------------+
```

In each case it appears as if the person may have had two roles at the station and instead of updating the existing person profile, a new profile was created. Unfortunately the WordPress plugin we're using for authors cannot handle two authors with the same exact name, or the same author with multiple profiles.

How shall I handle this?

**Comment by metastange** [comment]
You're correct - the duplicates were caused when contributors had different roles or re-joined staff at a later date. I've cleaned up the following:
-Reassigned associated posts to Nina Misuraca Ignaczak, deleted duplicate account
-Reassigned associated posts for Candice Fortman, deleted duplicate account
-Reassigned associated posts for Dorothy Hernandez, deleted duplicate account

Here's how to proceed on the other two accounts:
-I can't tell if Tia Graham's News Intern profile has any content associated with it; if it does, that content should be reassigned to her "Weekend Edition" host profile and the news intern profile can be removed. If there is no content associated with the news intern profile, remove it entirely.
-Both of Eryka Cheatham's user accounts can be removed; as far as I can tell, there is no content associated with her

**Comment by artlogic** [comment]
Here's the content I show associated with Tia Graham's intern profile:

```
+-------+---------------------+-------------+----------------------------------------------------------------------------------------------------------+
| id    | created             | status      | title                                                                                                    |
+-------+---------------------+-------------+----------------------------------------------------------------------------------------------------------+
| 83981 | 2016-10-11 17:43:07 | published   | Ford Fund Donates $5 Million for New Resource Center                                                     |
| 83988 | 2016-10-12 18:00:33 | published   | The Michigan State Police will participate in "National Prescription Drug Take-Back Day" on October 22   |
| 84012 | 2016-10-19 00:14:49 | published   | Lear Corporation opens a new innovation center in Downtown Detroit                                       |
| 84038 | 2016-10-21 15:10:13 | unpublished | The Detroit Office of Homeland Security and Emergency Management is planning to offer emergency training |
| 84080 | 2016-10-26 22:30:21 | unpublished | The City of Detroit is ramping up efforts to rid blighted buildings of graffiti                          |
| 84081 | 2016-10-26 22:36:16 | unpublished | Developers are working on a comeback for Detroits Old-Redford neighborhood                              |
| 84183 | 2016-11-15 16:17:43 | published   | A Northwest Detroit Coffee House is Brewing Again                                                        |
| 84216 | 2016-11-19 01:15:43 | published   | MSU Computer and Data Systems Breached                                                                   |
| 84374 | 2016-12-14 20:47:45 | published   | A Detroit Family Receives Fully Furnished Home For The Holidays                                          |
| 84758 | 2017-02-24 00:22:22 | published   | Detroit Lions and Verizon to offer free WiFi at Ford Field                                               |
+-------+---------------------+-------------+----------------------------------------------------------------------------------------------------------+
10 rows in set (0.00 sec)
```

Are you asking me to reassign and remove this content during the import, or will you be doing it prior to the import?

> Both of Eryka Cheatham's user accounts can be removed; as far as I can tell, there is no content associated with her

Will you be doing that in the old CMS or do you need me to take care of that?
