### ISSUE TITLE
Series + show pages manually built

### ISSUE THREAD

**Issue by wdet30** [arsmentis/wdet-conversion#36]
This is on target for the Monday eve update. 

TB

**Comment by artlogic** [comment]
I would suggest doing samples of these in layout for review. I expect a few more resets of the wdetcms site.

**Comment by wdet30** [comment]
Done

________________________________

**Comment by artlogic** [comment]
What will the URLs for these pages be?

**Comment by metastange** [comment]
All text. See attached for layout on current site:

![Screen Shot 2021-10-12 at 11 56 58 AM](https://user-images.githubusercontent.com/85897115/136989806-b96300ac-0bbb-4f4b-86e9-07ac29c23e77.png)

**Comment by artlogic** [comment]
> it appears that the short description and the long description were pulled into the same field; we don't need the short descriptions on the landing pages

I just pulled long_description - if there's a problem I suspect it's with the data in the old CMS
