### ISSUE TITLE
Dealing with Assets and Files (Media Folders)

### ISSUE THREAD

**Issue by wdet30** [arsmentis/wdet-conversion#38]
I'm coming across a lot of pages and post that have direct links to the asset folders. Please make sure that you copy all assets and media files over to the exact paths the old CMS and site was referring to.

https://wdet.org/media/wdet/assets/2020/ and so on

https://wdet.org/media/wdet/assets/2020/11/19/Banner_1000x300_CreatedEqual.jpg"

Please let me know we are good here. I don't want to use redirects for this.

T

**Comment by artlogic** [comment]
I think we'd better discuss this as I'm literally just about to start on this and I want everyone to be on the same page. We have several options:

1. Import every asset and podcast episode into the WordPress media library. Rewrite URLs in posts and other imported HTML to use the new media paths. Create redirects from the old /media/ URLs to the new WordPress URLs to handle anything missed or direct links.
2. Import only the assets that are strictly necessary. Copy the entire media folder to the new server. Perform no changes to content, and make no redirects for media.
3. Use some hybrid of the above to approaches.

Let me know what you're thinking.

**Comment by wdet30** [comment]
Lets go with Option 1. That will work fine for the static pages anyway. I'm having to download and upload the images and clean up the HTML anyway. If there is audio, I will do the same. The post have links to most assets so lets go with option 1 to make sure we get most of everything into Wordpress eco.


Thanks,
