### ISSUE TITLE
Review Redirect Import

### ISSUE THREAD

**Issue by artlogic** [arsmentis/wdet-conversion#39]
Please verify that redirects from the current CMS (as of July) are present in the new CMS.

https://wdetcms.wdet.org/wp-admin/tools.php?page=redirection.php

**Comment by artlogic** [comment]
Yup, those 74 redirects are exactly what I'm talking about.

**Comment by metastange** [comment]
> Was `/moth/` created recently?

Ope, yep, that was also a post-July addition (sorry, I didn't remember doing it). So we're all set on all fronts here!
