### ISSUE TITLE
How to transition post metadata audio player?

### ISSUE THREAD

**Issue by artlogic** [arsmentis/wdet-conversion#4]
Posts on the wdet.org site have a audio player that appears before a featured image: https://wdet.org/posts/2021/06/14/91073-secretary-of-state-benson-defends-controversial-changes-at-branch-offices/

We need to figure out how that audio will be displayed in the new WordPress theme. Please do a couple of experiments and let @artlogic know what you'd like to do.

**Comment by artlogic** [comment]
What's the update here @wdet30?

**Comment by metastange** [comment]
@wdet30 I am not seeing the native audio on post pages, please advise.

**Comment by wdet30** [comment]
Working on this.

**Comment by artlogic** [comment]
@wdet30 is thinking we'll do a custom field for this. I'll investigate how custom fields work, decide on a name, set up the import and do some basic theming. It'll probably be 8-12 hours of time.

**Comment by wdet30** [comment]
What works best

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by wdet30** [comment]
Yes thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by artlogic** [comment]
@wdet30 I won't be able to run another import until this is solved. I plan to work on it Saturday. Please let me know if you have any plans to work on this.

**Comment by wdet30** [comment]
I can't get on it til Sunday morning.

Thoughts?

________________________________

**Comment by artlogic** [comment]
I'll be looking for a solution today.

**Comment by metastange** [comment]
Any update on this front?

**Comment by wdet30** [comment]
I will get the plugin working tonight.

TB
________________________________

**Comment by metastange** [comment]
This issue came up during discussion about newsroom training: We want audio players to display below the headline and above the featured image, as they do on the current site, in order to encourage play conversion. We need to figure out how this works so we can train content staff.

Tony looking into plugins but needs approval from Jowana.

**Comment by artlogic** [comment]
I'm not sure if we need a plugin beyond ACF (and not the pro version). I'll see if I can get a demo.

**Comment by wdet30** [comment]
ACF probably can do both.

Get as far as you can with Demo. I will have full first thing tomorrow. Does that work?


________________________________

**Comment by artlogic** [comment]
Works for me.

**Comment by artlogic** [comment]
Here's an example of the audio being added to a post: https://wdetcms.wdet.org/2021/10/19/michigan-gop-lawmakers-pass-legislation-that-would-create-tax-credits-for-donors-giving-to-scholarship-programs/

Add the following below the `post-meta` div in `template-parts/post/content-parts/content-single.php`

```php
		<?php
		if ( get_field('featured_audio') ) :
		?>
		<audio controls>
  			<source src="<?php the_field('featured_audio'); ?>" type="audio/mpeg">
			Your browser does not support the audio element.
		</audio>
		<?php endif; ?>
```

**Comment by artlogic** [comment]
The import will require the creation of the custom field, as well as the custom field to be added to each post as required.

**Comment by artlogic** [comment]
@metastange waiting for you to review - I'm sure you'll want some style changes - also please review the process of adding featured audio to a post

**Comment by artlogic** [comment]
It's possible we could avoid the theme override by adding a filter to `the_title`.

**Comment by metastange** [comment]
Sorry, this one completely slipped by me.

Can we make the player the full width of the post? Otherwise it's fine with me.

Re: The process - the process is perf. I just did a test post and uploaded audio and it was simple and similar to the workflow the team is already used to. I also like that the audio will be stored in the media library (right now if you upload the audio tot the post, it's not accessible via "assets")

**Comment by artlogic** [comment]
@wdet30 

I think we just need to set `<audio>` tags to `width: 100%` here. Any objection?

**Comment by artlogic** [comment]
@wdet30 

Note that you'll need to add the following CSS to the child theme css:

```css
header audio {
	width: 100%;
}
```

@metastange Please take a look and make sure we're good: https://wdetcms.wdet.org/2021/11/11/audio-test/

**Comment by wdet30** [comment]
@artlogic All Good on the header audio css.

**Comment by wdet30** [comment]
> Here's an example of the audio being added to a post: https://wdetcms.wdet.org/2021/10/19/michigan-gop-lawmakers-pass-legislation-that-would-create-tax-credits-for-donors-giving-to-scholarship-programs/
> 
> Add the following below the `post-meta` div in `template-parts/post/content-parts/content-single.php`
> 
> ```
> 		<?php
> 		if ( get_field('featured_audio') ) :
> 		?>
> 		<audio controls>
>   			<source src="<?php the_field('featured_audio'); ?>" type="audio/mpeg">
> 			Your browser does not support the audio element.
> 		</audio>
> 		<?php endif; ?>
> ```

@ line 57

**Comment by artlogic** [comment]
I will be using a filter for this, please hold

**Comment by artlogic** [comment]
@wdet30 unfortunately I can't do this with a filter, so we'll need to use the override as documented above.

**Comment by artlogic** [comment]
Data is being included with posts via 821c380488e73ad1e3e7dda3762cf552dd5502c2

**Comment by artlogic** [comment]
Config is included with 8afb1e8b69f53644987fa90debca24efa6d41739

This should be complete on my end - removing my assignment - re-add if needed.

**Comment by wdet30** [comment]
@artlogic, I'm looking to ad the updated page to wdetcms. Would you please copy the file below to the child theme?

/opt/www/wordpress/wp-content/themes/tony-brown-news-pro-35/template-parts
File
[content-single.php ](https://github.com/arsmentis/wdet-conversion/commit/87ab3706d2f2b33ceb1d198f7fd940ae10c2baa0)

Thanks

**Comment by artlogic** [comment]
I'm curious, is this something that can't be added to the child theme's zip file?

**Comment by wdet30** [comment]
Man I'm creating the child theme manually from scratch. I don't have permissions to move the file to the server.
________________________________

**Comment by artlogic** [comment]
I'll create a zip file and show you how it can be done.

**Comment by wdet30** [comment]
I don't really need to do the zip thing because I have been building it up manually. The only thing that needs to be done that I can't do is move that file over. Please let me know if you can get that over that's all I need.


________________________________

**Comment by wdet30** [comment]
I'm aware of the download the files and zip it up technique I'll give that a try.


________________________________

**Comment by wdet30** [comment]
The theme has been updated and converted to zip for ease of use. @artlogic

**Comment by metastange** [comment]
@wdet30 audio custom field not showing up on wdetcms (embedded player below the headline). Please advise.

**Comment by wdet30** [comment]
@***@***.******@***.***> please advise on this did I miss something here.
________________________________

**Comment by artlogic** [comment]
I don't see the file I referenced above: https://github.com/arsmentis/wdet-conversion/issues/4#issuecomment-967702466

**Comment by artlogic** [comment]
@wdet30 added the content-single.php to the proper location and committed it.

I don't see a CSS file that you're enqueuing so you will have to add the see I referenced above.

**Comment by artlogic** [comment]
Well - it looks like the way I fixed this before isn't work - I believe that some theme setting is different (probably the heading style). Is there a list of the settings that are being changed within the theme? Especially with us doing theme overrides these can affect things dramatically and break things that were working.

I want to make sure that if I fix this, that it's going to work when we hit production and not break again because of a theme setting that was set or unset inconsistently.

**Comment by wdet30** [comment]
The only changes made now are:

header.php
custom code.css
the excerpt override in functions

That's all I have now.

________________________________

**Comment by artlogic** [comment]
There are a ton of settings in the Customize section that aren't represented by the theme files. Something has changed from the last deployment. I think we need a list of what's being changed from default here.

My guess is that last deployment the single post heading was set to classic, and now it's set to standard, but I haven't sorted this out yet. I will not be able to look into this deeply until tonight.

**Comment by wdet30** [comment]
Copy

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by metastange** [comment]
I don't know if this helps or hurts, but here are notes on the settings I used on Customizer for reference. These would not have been included in the last deployment, as the template was created on layout.

Site Header settings
	• Disable Header top bar
	• Logo and Menu - style 2, active sticky menu
	• News ticker visibility - hide
New Box Home Settings
Slider grid settings
	• Home slider grid
	• Latest post
	• 1
	• Category for featured right grid: news
	• Four items
	• Feature news image zoom
Home news tab section one
	• Title: recent
	• Tab 1 category - latest
	• Tab 2 category - Detroit Today
	• Tab 3 category - CultureShift
	• Post number 6
	• Tab menu style - style 1
	• Tab content style - style 3
	• Show date
Blog Settings
	• Full width container
	• Right sidebar
	• Header position left
	• List blog style
	• No shadow or border
	• Title position left
	• Post time,read more
Home bottom section
	• Most Popular
	• Popular post
	• 4
	• 4 column
	• Style 2
	• Show date
	• Active image hover
Homepage settings
	• Your latest posts
General Settings
	• Page settings - reduce page header padding
Site 404 page
	• 404 text
	• 404 text: Page not found
	• 404 heading: Oh no! We can't find the page that you requested.
	• 404 page description: Try searching to find what you're looking for:
	• Display 404 page search field

**Comment by artlogic** [comment]
I'm concerned about this. However this isn't the place to discuss that.

I will need to find another way to make this change that's resilient to theme settings being changed.

**Comment by artlogic** [comment]
Should be working now - but needs verification and styling.

**Comment by metastange** [comment]
Confirming the audio is showing up on post pages. Will this addition be impacted by Customizer?

Not sure how to advise on styling as I'm not sure how customizable this function is.

**Comment by wdet30** [comment]
@artlogic well done.

**Comment by artlogic** [comment]
@metastange customizer shouldn't impact this - let me know if we need anything further here - otherwise I'll close this one.

**Comment by metastange** [comment]
all set.
