### ISSUE TITLE
Review Author/Person Import

### ISSUE THREAD

**Issue by artlogic** [arsmentis/wdet-conversion#41]
Review the author/person import from the old site, verifying the following:

- [x] Imported people are correctly represented (including bio info) as authors
- [x] Redirects from old author URLs to new author URLs work properly
- [x] Authors who are also users in the system are associated correctly

https://wdetcms.wdet.org/wp-admin/edit-tags.php?taxonomy=author

**Comment by metastange** [comment]
Oops, sorry @artlogic, I'm working from the bottom up, so I put notes on this on issue #27. Moving notes here.

**Comment by artlogic** [comment]
No worries - I've gone ahead and added the notes here:

> @artlogic - i'm noticing issues with the author urls (for example, Alex Trajano's author url is ccampbell). Also noticing issues with images (for example, my picture is associated with Anthony Spak's profile.) Do you want me to document them here or manually change them myself? also at this point in the import process, should there be posts associated with the authors? (https://github.com/arsmentis/wdet-conversion/issues/27#issuecomment-944371918)

> Alex Trajano's author url is ccampbell

This looks like a problem on my end - I will look into it.

> my picture is associated with Anthony Spak's profile

I don't see an author by the name of Anthony Spak - could you give me a link?

Please document any issues you find here and I'll look into them. Posts should be associated with authors.

**Comment by dorothyhernandez** [comment]
Question: Should WDET staffers e.g. Russ McNamara be listed as a guest author? I saw a bunch like that but wanted to check before I added to my list.

I compiled all of the issues I saw in this Google doc (too much to dump into comments here). It's mostly of profiles not linked to the right user e.g. Pat Batcheller is linked to mapped user Quinn Klinefelter and when you hit the author url it goes to the wrong page. E.g. Pat's profile has this author url: https://wdetcms.wdet.org/author/qklinefelter/

Google doc: https://docs.google.com/spreadsheets/d/14Z6AKOhfmtXmio_bpJIQRsiOr6h-BY-EV0WEKgYHCcM/edit?usp=sharing

**Comment by artlogic** [comment]
> Question: Should WDET staffers e.g. Russ McNamara be listed as a guest author? I saw a bunch like that but wanted to check before I added to my list.

In the data dump I have (from July) Russ's person profile is not linked to a user. That's why he's showing up as a guest author. I would suggest linking him properly in the CMS.

I will be pulling a new data dump soon, and running a new import. That should resolve this issue as long as the old CMS is updated.

**Comment by metastange** [comment]
@artlogic reviewing something different and came across and author issue:

This post is showing up on the backend with "Laura" as the author, but Dorothy is bylined on the front end:

New: https://wdetcms.wdet.org/2021/10/06/detroit-wants-to-restore-historic-home-of-ossian-sweet-to-teach-others-about-housing-discrimination/
Current: https://wdet.org/posts/2021/10/06/91514-detroit-wants-to-restore-historic-home-of-ossian-sweet-to-teach-others-about-housing-discrimination/

Not sure if i need to make a new issue for this?

**Comment by artlogic** [comment]
@metastange after investigating, all I can think is that someone manually changed the author on this post after the import. Unfortunately WordPress doesn't have a built in audit trail, so there's no way to know if that actually happened. It's seeming like there might be one more import prior to launch given the few issues we've found. I'd appreciate it if you would keep an eye on this post and let me know if it looks incorrect after the next time we import data.

**Comment by metastange** [comment]
Wait, that's super weird, it had "Laura Herberg" as the author on the backend when I made this post, but now it's showing Dorothy on both the back and front end. I will keep an eye on this one.

**Comment by artlogic** [comment]
Most CMSes that are used by many people have some kind of an audit log or trail to prevent just these sort of things. Maybe @wdet30 knows of a good plugin for us to use that will provide that?

**Comment by metastange** [comment]
This issue has largely been resolved, but would like clarity from @wdet30 on whether there's a plugin for an audit log.

**Comment by wdet30** [comment]
I'm going to hold this and do a little more research.

Sorry I don't have the answer at the moment.
________________________________

**Comment by artlogic** [comment]
Let's close this then, and open a new issue for the audit log plugin if that's OK?
