### ISSUE TITLE
Review Asset Import - stage 1

### ISSUE THREAD

**Issue by artlogic** [arsmentis/wdet-conversion#42]
Over half of the assets in the old CMS are being imported as a byproduct of importing authors and posts. Please verify:

- [x] Images with the same title in the old CMS are actually the same image
- [x] Image metadata is correct and matches the old CMS

https://wdetcms.wdet.org/wp-admin/upload.php

**Comment by artlogic** [comment]
6000 is a lot - I would suggest spot checking a certain percentage - I would think maybe just 1% would be enough, along with checking posts as well.

> there are a large number of assets associated with posts that are not here. Is that to be expected at this point?

Can you be more specific? Is this the same as #7 ?

**Comment by artlogic** [comment]
How are you determining the association?

**Comment by metastange** [comment]
Reviewed asset import and it appears that Source/Licence URLs did not transfer over:
Examples:
old: https://wdet.org/admin/wdet/asset/16353/?_changelist_filters=p%3D3
new: https://wdetcms.wdet.org/wp-admin/upload.php?item=17367

old: https://wdet.org/admin/wdet/asset/1437/?_changelist_filters=q%3Ddetroit%2Bzoo
new: https://wdetcms.wdet.org/wp-admin/upload.php?item=11824


It also appears that tags on from the current CMS did not make it to the new:
Examples:
old: https://wdet.org/admin/wdet/asset/5402/?_changelist_filters=q%3Dwater
new: https://wdetcms.wdet.org/wp-admin/upload.php?item=13449

old: https://wdet.org/admin/wdet/asset/54/?_changelist_filters=q%3Dlisa%2Bbrancato
new: https://wdetcms.wdet.org/wp-admin/upload.php?item=1014

**Comment by artlogic** [comment]
> Reviewed asset import and it appears that Source/Licence URLs did not transfer over

I can transfer these over, but we only have 3 places to put them:
* Alternative Text (probably the wrong choice)
* Caption
* Description

If you want a discrete field for Source/License URL, that may be something to speak with @wdet30 about.

> It also appears that tags on from the current CMS did not make it to the new

As I've said before, I simply have no way to transfer tagging over. WordPress does not natively allow you to tag media. I was under the impress we were waiting on a plugin for this functionality. Can you provide any insight @wdet30?

**Comment by metastange** [comment]
Closing the loop on one of the above: Not concerned about the lack of tags on the assets during the import.

**Comment by artlogic** [comment]
I created issue #69 for dealing with the source/license URLs

**Comment by metastange** [comment]
Closing this since the outstanding issues have individual tickets (#69 #71 )
