### ISSUE TITLE
Show Pages review

### ISSUE THREAD

**Issue by wdet30** [arsmentis/wdet-conversion#47]
Hello, I'm looking to get get Q&A going on the show pages only.

A description of a show page is a product that is on air. A show page is a static page with the description of the show with a link to the staff page or syndicated website. A show can have a podcast attached to it.  The main elements of a show landing page below.
**Looking to verify:**
• Show banner
• Show times 
• Description of show 
• Link to show and or host.
• Blog post widget. (Querying the latest posts of the show or podcast. IE: blog post to category) 
• Playlist widget if it is a show.
• Donation template
• Please report any styling issues or missing show information. Did I miss any shows?

Here is a easy link to all the shows: https://layout.wdet.org/wdet_shows/

I emailed you a doc for Q&A or use this here: https://docs.google.com/spreadsheets/d/1Mn3GE9EvKJ2Mokv0kmrI4HsnmTZu_zTXYrq8uK150sw/edit?usp=sharing

**Comment by wdet30** [comment]
Copy

________________________________

**Comment by metastange** [comment]
@wdet30 I've completed my desktop review of all available shows (as noted in the doc, the page is currently missing all shows that come alphabetically after "The Moth" - The Treatment, This American Life, This Island Earth, Wait Wait Don't Tell Me, Weekend Edition).

So everyone is on the same page: there are a LOT of updates that @dorothyhernandez and/or I can take care of that I'm flagging now because it's not often that I'm looking at all of these pages at the same time and I'm finding a lot of inconsistencies. Anything in RED are the pressing site-layout-related issues.

**Comment by dorothyhernandez** [comment]
I need edit access to the Google doc, not the CMS (I'm in the CMS rn without any problems).

https://docs.google.com/spreadsheets/d/1Mn3GE9EvKJ2Mokv0kmrI4HsnmTZu_zTXYrq8uK150sw/edit#gid=1308127726

**Comment by wdet30** [comment]
@dorothyhernandez , having trouble with your WDET email. Please hit me with your Gmail address

**Comment by dorothyhernandez** [comment]
@wdet30 sorry I just saw this. It's dlhernandez@gmail.com

**Comment by artlogic** [comment]
Let's try to align this with the next data dump/import. After I complete my import, you can install your theme and copy over the show/series pages.

**Comment by artlogic** [comment]
I think that's going to be up to @metastange and @dorothyhernandez - I will send out an update within the hour.

**Comment by wdet30** [comment]
@metastange @dorothyhernandez @Jazzyhunt, we have made a list of changes to just the Show pages. You are free to edit them. 

FYI: We have not updated the grid.

Please do and updated Q&A and edit, only on these pages linked on this WDET Shows Landing page.
 https://layout.wdet.org/wdet_shows/
Thanks

**Comment by metastange** [comment]
@wdet30 - I've conducted an updated QA. I don't know why the "copy" column was removed from the QA document, but it had information that I planned to implement on the new pages; moving forward can you let me know if you're going to remove information from QA documents so I can save that info on my side?

Just confirming - you want me to edit show pages on the layout site? If yes, I can make copy and some layout changes and reflect them in the doc.

**Comment by metastange** [comment]
@wdet30 Show pages have been updated, the only outstanding thing we'll need from your team is to ensure that the content blocks are pulling in the correct show content.

**Comment by wdet30** [comment]
Sounds great,  Thanks.

FYI: I won't connect the show content until we move to the live site. The query won't export, I must set them up manually.

TB

________________________________
