### ISSUE TITLE
Podcast pages for review

### ISSUE THREAD

**Issue by wdet30** [arsmentis/wdet-conversion#50]
Hello @metastange @dorothyhernandez,. looking to Q&A our podcast pages and the landing page.
https://layout.wdet.org/wdet-podcasts/

Please feel free to edit.

Looking to verify:
• Show banner
• Show times
• Description of show
• Link to show and or host.
• Blog post widget. (Querying the latest posts of the show or podcast. IE: blog post to category)
• Playlist widget if it is a show.
• Donation template
• Please report any styling issues or missing show information. Did I miss any shows?

https://layout.wdet.org/wdet-podcasts/

**Comment by wdet30** [comment]
@wdet30 on this now.

**Comment by wdet30** [comment]
all set

**Comment by metastange** [comment]
@wdet30 - I've reformatted all podcast landing pages and made the bulk of the styling/content QA updates listed in the doc. Anything highlighted in RED is what I need additional assistance from you on (mainly adding players and content blocks). Yellow highlights are Dave's deliverables and can be added post-launch.

https://docs.google.com/spreadsheets/d/1Mn3GE9EvKJ2Mokv0kmrI4HsnmTZu_zTXYrq8uK150sw/edit#gid=791902652

**Comment by metastange** [comment]
Closing to add one global to-do about adding the related content modules for all show, podcast and series pages
