### ISSUE TITLE
Station Pages  - Easy link

### ISSUE THREAD

**Issue by wdet30** [arsmentis/wdet-conversion#52]
Hello everyone, here is a link to all the station related pages. This will make it easy to Q&A and find pages that are not show, podcast or series pages. 

Here is the link. https://layout.wdet.org/station-pages/

**Comment by metastange** [comment]
FYI, tracking updates that need to be made in this document:
https://docs.google.com/spreadsheets/d/1Mn3GE9EvKJ2Mokv0kmrI4HsnmTZu_zTXYrq8uK150sw/edit#gid=1898546819

Added an assignment column to more clearly identify what Dorothy and I can manage (and what we need to call in additional team members to weigh-in on).

**Comment by wdet30** [comment]
Ok thanks. T

________________________________
