### ISSUE TITLE
Review Import Errors

### ISSUE THREAD

**Issue by artlogic** [arsmentis/wdet-conversion#54]
Please review: https://github.com/arsmentis/wdet-conversion/wiki/Import-Errors

These are 99% errors importing assets and I still have a few additions to make to this list (there's a part 5 and 6 that are currently missing). I would suggest reviewing the particular assets on the old CMS and determining what the problem is, and if it's worth fixing. Here's an example:

1. In the old CMS search for the title: Governor General David Johnston 042815
2. Click and open the main asset page: https://wdet.org/admin/wdet/asset/778/
3. In this case notice that the image ( https://wdet.org/media/wdet/assets/2015/04/30/Governor_General_David_Johnston_042815.jpg-large ) has a strange extension: **.jpg-large**
4. Open the image and save it on your machine
5. Change the extension to **.jpg**
6. Update the asset on the old CMS - you should see the link change.

If it's important to pull these assets in, each one will need to be reviewed and fixed in a similar way - it's posible it'll be a number of different problems (not just file extensions). I'm happy to help if there are questions.

**Comment by artlogic** [comment]
@metastange I successfully was able to import the missing file on my test server and two more issues were reported:

* Failed to import Media “Liesl Clark Michigan EGLE Environment Great Lakes Energy jn”
* Failed to import Media “Christophe Zajac-Denek headshot bust”

I've also updated the wiki page linked above.

**Comment by metastange** [comment]
Updated both on the current site.

**Comment by artlogic** [comment]
Great! I think we can close this for now.
