### ISSUE TITLE
Host info & showtimes in sidebar discontinued 

### ISSUE THREAD

**Issue by wdet30** [arsmentis/wdet-conversion#61]
@metastange @dorothyhernandez , we are going to have to discontinue the host & show info in the sidebar. We would have to create and manage a sidebar for very show.  

Please see this page on how to resolve this. 
1. Create a section in elementor underneath the banner, use the text editor widget and add show information and style to taste.

example:
[https://layout.wdet.org/wdet_shows/ann-delisis-essential-music/](https://layout.wdet.org/wdet_shows/ann-delisis-essential-music/)

**Comment by metastange** [comment]
So that means we're not able to add contact, links or social info either, correct? Those should be manually added to each page?

**Comment by wdet30** [comment]
Nope, need to be in the body. Section need to be created to accommodate.

Tony

________________________________

**Comment by wdet30** [comment]
Closing this.
