### ISSUE TITLE
Series and Show Linking Review

### ISSUE THREAD

**Issue by artlogic** [arsmentis/wdet-conversion#63]
I want to verify the following situation is intended and acceptable:

Here's an example of a post that is linked to a show: https://wdetcms.wdet.org/2021/10/19/black-is-beautiful-exhibition-at-detroit-institute-of-arts-highlights-1960s-cultural-movement/

The show link is listed at the top (CultureShift). When you click on it, you end up at the category page, here: https://wdetcms.wdet.org/category/shows/cultureshift/

This category page is not the same as the show page here: https://wdetcms.wdet.org/wdet_shows/cultureshift/

The situation is the same for every post that's a part of a series or show.

**Comment by wdet30** [comment]
Checking


________________________________

**Comment by artlogic** [comment]
I'll set up an experimental redirect and from the category page to the static show page and we'll see if this is a good solution.

**Comment by artlogic** [comment]
I will create a few tests on wdetcms to see if we can use redirects to bypass category pages entirely.

**Comment by wdet30** [comment]
I'm wondering how that's going to affect pulling data from those categories into side bars grids and modules not limited to RSS feeds.


TB
________________________________

**Comment by artlogic** [comment]
@metastange @wdet30  I've added a CultureShift redirect on the WDETCMS site. Please take a look and if this works properly, it should be trivial to add the rest, and it could even be automated. Let me know what you find and I'll explain the full plan once I hear back.

**Comment by wdet30** [comment]
ok

________________________________

**Comment by wdet30** [comment]
@artlogic Working great on site and we are good no issues on the redirects.
Link to RSS feed for category
https://layout.wdet.org/category/shows/cultureshift/rss

**Comment by artlogic** [comment]
Does the rss still work on CMS?

**Comment by wdet30** [comment]
Yep working great:

https://wdetcms.wdet.org/category/shows/cultureshift/feed/

https://wdetcms.wdet.org/category/shows/cultureshift/RSS

**Comment by metastange** [comment]
Redirect is working for me when I test it on the front-end.

**Comment by artlogic** [comment]
Here's the plan moving forward then:

* I'll make several changes to the import:
   * Stop populating category descriptions
   * Stop redirecting old shows and series to new category pages - but continue to do that with topics
   * Create a new set of redirects that redirect from category pages for series and shows to the old links (essentially the reverse of what I do now).
* I need @wdet30 to make sure all the show and series URLs are **identical** to those on the old web site (currently they are not). We'll want @metastange to verify this once it's been done.

@wdet30 and @metastange - please let me know if this works for you?

**Comment by wdet30** [comment]
Absolutely and it'll be the first thing I do in the morning get all those URL set. I actually think I'm good there. But I'll double check and verify.

Thanks

________________________________

**Comment by artlogic** [comment]
My work is done on this issue with the prior linked commit  - removing my assignment. Verification of redirects in particular are still required.

**Comment by metastange** [comment]
i've reviewed all redirects and all look good. There are two categories that have duplicative TAGS (curiosiD and storycorps Detroit) and i've made a note to remove these tags post-launch.
