### ISSUE TITLE
Publish times are being offset incorrectly 

### ISSUE THREAD

**Issue by artlogic** [arsmentis/wdet-conversion#64]
The old CMS publish times appear to be in Eastern time, however the importer is not interpreting them correctly - for example:

Post: Detroit Police Officer Suspended After Fleeing from Fellow Officers During Traffic Stop
Published on 2021-09-16 16:26:04

```xml
      <wp:post_date>2021-09-16 20:26:04</wp:post_date>
      <wp:post_date_gmt>2021-09-17 00:26:04</wp:post_date_gmt>
      <wp:post_modified>2021-09-16 20:36:17</wp:post_modified>
      <wp:post_modified_gmt>2021-09-17 00:36:17</wp:post_modified_gmt>
```

The non UTC dates are being offset as I would expect UTC to be, and the UTC posts are offset by double.

**Comment by wdet30** [comment]
@artlogic, make sure you have the time zone set properly in WordPress before you import. I hope this helps.
https://wdetcms.wdet.org/wp-admin/options-general.php

**Comment by artlogic** [comment]
Half of this issue is resolved (the UTC times are correct now).
