### ISSUE TITLE
Tagging Best Practices - Training

### ISSUE THREAD

**Issue by metastange** [arsmentis/wdet-conversion#66]
Can you advise on guidelines for tagging for content creators? The old site was all over the place. Do they need to include any quotation marks, #, etc? Any insight you can provide so we can integrate that into training would be great.

**Comment by wdet30** [comment]
@metastange, we don't need to add the #hastag or quotes when tagging in WordPress. But, please stress that you should search for a tag before creating a new one.  Tags can easily search or created using the tag field in a post on the right hand side when you are editing or creating a post.

More Info on Tags in Wordpress:
Tags are much more specific topics that you want to use to associate related content. For example if you were creating a site that reviews music, use tags such as jazz music or rock music reviews or music reviews.

You can combine the two! For our review site example, you might be reviewing a romantic comedy. You can assign the broader category Film to the post, then give it some more specific tags such as romantic comedy, or even use the name of the actors and director as tags. People who view that post could use the tags to then find relates posts around that topic.

There is more info here that should be passed on:
Tags are used to describe your post in more detail. Tags should not be used to categories a post, story or content.

https://wordpress.com/support/posts/tags/

Also Categories vs. Tags
https://wordpress.com/support/posts/categories-vs-tags/



https://wordpress.com/support/posts/categories-vs-tags/
