### ISSUE TITLE
Authors are being duplicated at the bottom of articles

### ISSUE THREAD

**Issue by artlogic** [arsmentis/wdet-conversion#68]

**Comment by wdet30** [comment]
@artlogic, I have no idea why this is happing. Can you debug a little more and advise? 

TB

**Comment by artlogic** [comment]
Will do - but this'll be hourly, FYI.

**Comment by wdet30** [comment]
Sounds good to me.

TB
________________________________

**Comment by artlogic** [comment]
@wdet30 

Partial fix: turn off "Show single post author bio?" in Single Blog Settings for the theme.

**Comment by artlogic** [comment]
Actually that's a total fix - along with making sure only one Authors plugin is installed. There were two installed on the CMS site. I disabled one.

@wdet30 - assigning to you. I don't think I have anything else to do here.

**Comment by wdet30** [comment]
One is the base version and the other is the pro version which unlocks all the features.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by artlogic** [comment]
> One is the base version and the other is the pro version which unlocks all the features.

Well I uninstalled the base version and it's still working OK for me.

**Comment by wdet30** [comment]
Yep I think you just need to deactivate it but if it's working fine. Sometimes those base versions need to be on the server but not activated but if it's working we are good.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by artlogic** [comment]
No need to keep the free version on the server. Deactivated plugins are still a liability.

**Comment by wdet30** [comment]
Okay

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
