### ISSUE TITLE
Show media descriptions for featured images

### ISSUE THREAD

**Issue by artlogic** [arsmentis/wdet-conversion#70]
Related to #69

**Comment by artlogic** [comment]
Looks like this might help: https://napitwptech.com/tutorial/wordpress-development/display-image-caption-added-wordpress/

**Comment by wdet30** [comment]
Like this

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by wdet30** [comment]
@artlogic , what do you think of this plugin?
https://wordpress.org/plugins/fsm-custom-featured-image-caption/ will this do the job?

**Comment by artlogic** [comment]
You'd have to test it. It's unclear how it will work for featured images.

**Comment by wdet30** [comment]
ok will test get back to it Sunday am

**Comment by artlogic** [comment]
I don't believe this is relevant any longer. Closing in favor of #69.
