### ISSUE TITLE
Dealing with #11 #14 lead in & Metadata

### ISSUE THREAD

**Issue by wdet30** [arsmentis/wdet-conversion#72]
@artlogic,
It looks like the solution is custom fields WordPress? This applies to both of #11  & #12 . My goal is to have James map both sets of data to separate custom fields in WordPress post. I will try to do an easy **<hr> bold style** for the lead-in. I'm not sure what the audio meta data will look like.

First, I'm hoping you can pull the data in so I can investigate:
Do I need any additional styling to accommodate the audio player?
How much styling do I need for the <hr />Lead in text....<hr />?
How to pull the custom filed into WordPress post only and flow with the theme?

Is it possible for you to move forward with this weekend dump and we look at this on Sunday and Monday?

Please advise

**Comment by artlogic** [comment]
I already pull custom fields into WordPress for the author plugin. It's trivial. But I can't pull in custom fields that I don't know the names of. Are you asking for me to make the decisions here?

Additionally - why do we need a custom field for lead ins? Can't we just use `the_excerpt()` - https://developer.wordpress.org/reference/functions/the_excerpt/ - do you need help getting that themed in?

**Comment by wdet30** [comment]
Yes please,

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by artlogic** [comment]
I'm going to close this issue, and move conversation to #4 because I think #11 is basically a theming issue at this point.
