### ISSUE TITLE
Get dev server setup with vanilla WordPress

### ISSUE THREAD

**Issue by artlogic** [arsmentis/wdet-conversion#73]
Should be done by the 12th.

**Comment by artlogic** [comment]
@wdet30 wordpress install is complete

https://wdetdev.wdet.org/

**Comment by wdet30** [comment]
Copy

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by wdet30** [comment]
@artlogic , I'm having trouble installing or making changes to the Dev WordPress build. Please see the screenshot of my error.
![WP-instal-1](https://user-images.githubusercontent.com/84190532/142892674-965ace95-4029-40e3-8088-6616f13dff5a.png)

**Comment by artlogic** [comment]
@wdet30 can you create an ID so I can see what's going on here? It's likely SELinux.

**Comment by wdet30** [comment]
What do mean ID? I'm not sure what you are looking for?

TB
________________________________

**Comment by artlogic** [comment]
A login ID.

**Comment by wdet30** [comment]
My bad, all set.

TB
________________________________

**Comment by artlogic** [comment]
This should be working now - please confirm.

**Comment by wdet30** [comment]
Working like gold in the old west.

**Comment by wdet30** [comment]
@artlogic, I hate to do it but I'm still having troubles uploading plugins. I'm getting this: 

*The uploaded file exceeds the upload_max_filesize directive in php.ini.**

TB

**Comment by artlogic** [comment]
What size do you think you need? I can get it updated in an hour or so.

**Comment by wdet30** [comment]
How about 5gb. Just in case we Have to upload a big video or 1 hour audio.

Thanks,
Tony
________________________________

**Comment by artlogic** [comment]
Please re-open if any further issues.

**Comment by wdet30** [comment]
@artlogic , I'm having trouble resetting my password on the Dev site.
https://wdetdev.wdet.org/

Would you please please help reset for my user: tony.brown@wdet.org

Thanks

**Comment by artlogic** [comment]
I have no access beyond either resetting the entire site or resetting the password manually via the database. What do you want me to do?

**Comment by wdet30** [comment]
What is the easy way? What works for you?

Let me now. I will text you the password if you want to do database.

**Comment by artlogic** [comment]
Erasing the entire database is likely a bit easier

**Comment by wdet30** [comment]
All good, let me now my next move. T

**Comment by artlogic** [comment]
Looks like I can't SSH into wdetdev. I'm contacting Marty about this.

**Comment by wdet30** [comment]
Copy

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by artlogic** [comment]
You should be good to go.

**Comment by wdet30** [comment]
@artlogic , when you get a chance no hurry would you please change the upload and import size to 10gb? or as high as you recommend? I'm getting the upload size error.

**Comment by artlogic** [comment]
10gb is pretty big. I normally recommend only as small as possible.

**Comment by wdet30** [comment]
2gb please that's enough for a 20min video.

**Comment by artlogic** [comment]
Even that size is a security/stability concern. However I'll set it to whatever you like.

**Comment by wdet30** [comment]
Thanks again
