### ISSUE TITLE
Lightboxes + Notification Bar

### ISSUE THREAD

**Issue by metastange** [arsmentis/wdet-conversion#74]
@wdet30 Can you provide insight about what features on the new site will be similar to the lightboxes/notification bar on our current site?

**Comment by wdet30** [comment]
The breaking news feature will be the new notification bar. We can turn on off or change message at your discretion. The lightbox I'm down to 3 will have that installed on Thursday.

**Comment by wdet30** [comment]
Let my know what specs you want to use it's a universal lightbox.

Just just making image and I will be able to turn it into a light box. Provide me the image that you're looking to Popup.



________________________________

**Comment by wdet30** [comment]
@metastange, making this important due  that you need this buy Tuesday.

**Comment by wdet30** [comment]
@metastange, here is the link to edit the universal lightbox.

https://layout.wdet.org/wp-admin/post.php?post=24435&action=elementor
