### ISSUE TITLE
Training - How to Add an Anchor Link to Jump to a Specific Part of a Page

### ISSUE THREAD

**Issue by metastange** [arsmentis/wdet-conversion#78]
Clarify process for adding an in-post anchor. Example can be found on the current site here: https://wdet.org/posts/2021/11/02/91651-michigan-november-2-election-results/

**Comment by wdet30** [comment]
@dorothyhernandez, are you guys codding the HTML for the anchor text into the post? How are you doing it now?

Thanks, T

**Comment by wdet30** [comment]
There are many ways to do this in WordPress. You can do continue to do so like you did on the old site, or use one of the options below.


Option 1:
[https://layout.wdet.org/2021/11/14/how-to-manually-add-anchor-link-in-classic-editor/](https://layout.wdet.org/2021/11/14/how-to-manually-add-anchor-link-in-classic-editor/)

Option 2:
[https://www.w3docs.com/snippets/html/how-to-create-an-anchor-link-to-jump-to-a-specific-part-of-a-page.html](https://www.w3docs.com/snippets/html/how-to-create-an-anchor-link-to-jump-to-a-specific-part-of-a-page.html)

**Comment by metastange** [comment]
@wdet30 we are not currently coding HTML for anchor text in posts; continuing to do what we do on the old site does not appear to be an option, so we will consider the options provided above. Thanks.
