### ISSUE TITLE
Categories Search Function

### ISSUE THREAD

**Issue by metastange** [arsmentis/wdet-conversion#83]
Make "Categories" a searchable field (like tags) on the backend.

**Comment by wdet30** [comment]
@metastange, this has been completed. Please see the attached image for location.
![number_83](https://user-images.githubusercontent.com/84190532/141709671-d661e9c1-e13c-4a35-8c76-424223575e5d.png)



TB

**Comment by metastange** [comment]
Awesome, thanks!
