### ISSUE TITLE
Update pages from doc - Test

### ISSUE THREAD

**Issue by wdet30** [arsmentis/wdet-conversion#85]
@Jazzyhunt, this is test.

- [ ] update pages on doc
- [ ] update images where need

**Comment by wdet30** [comment]
Here is the doc.
https://docs.google.com/spreadsheets/d/1Mn3GE9EvKJ2Mokv0kmrI4HsnmTZu_zTXYrq8uK150sw/edit#gid=1308127726

**Comment by Jazzyhunt** [comment]
testing

**Comment by wdet30** [comment]
@Jazzyhunt, how is Github working for you?

**Comment by Jazzyhunt** [comment]
I think it is working well.
