### ISSUE TITLE
Run final import and develop timing and checklist

### ISSUE THREAD

**Issue by artlogic** [arsmentis/wdet-conversion#87]

**Comment by artlogic** [comment]
I've started a checklist here: https://github.com/arsmentis/wdet-conversion/wiki/Transition-Checklist

**Comment by artlogic** [comment]
Note to self: limit export to only needed tables - get a list created.

**Comment by artlogic** [comment]
My portion of this is done - assigning to @wdet30 and @metastange in case there are things that need to be added that I'm not aware of.

**Comment by metastange** [comment]
I am reviewing the content now - at a cursory glance, the data looks correct but there are issues with how it's populating on the front end (ie the native audio is being transferred over, but not showing up on the audience-facing post). Should we use this thread to document those issues? @artlogic @wdet30

**Comment by wdet30** [comment]
I guess for me if you have any issues with the pages any data didn't come through with that import another issue would work for me.
But whatever works for both of you.
________________________________

**Comment by artlogic** [comment]
@metastange if you could open new issues (or use the existing ones) that would be ideal.

**Comment by metastange** [comment]
@artlogic I added my pre-launch review list to the checklist above; i think that's pretty much it but will continue to add if i think of anything else.

**Comment by metastange** [comment]
Added estimated QA timing (1.5-2 hours).

**Comment by artlogic** [comment]
@wdet30 and @metastange - does the document look to be complete for you? If so let's close this issue, and we can verify the times we recorded next week.

**Comment by wdet30** [comment]
Looks good here thanks.


________________________________

**Comment by metastange** [comment]
i'm good on my end; closing.
