### ISSUE TITLE
Failed to import Media

### ISSUE THREAD

**Issue by wdet30** [arsmentis/wdet-conversion#90]
Failed to import Media “npr-logo”
Failed to import Media “Spotify_logo_without_text”
Failed to import Media “Podcasts_(iOS)”
Failed to import Media “google-podcasts”
Failed to import Media “A-Logo-19102020.svg”
Failed to import Media “Menu.svg”

**Comment by wdet30** [comment]
@Jazzyhunt, would you please update pages that didn't carry over these images.

Mainly Podcast pages.

**Comment by Jazzyhunt** [comment]
Yes, working on that currently.

**Comment by wdet30** [comment]
Did you get the images ok?
________________________________

**Comment by Jazzyhunt** [comment]
Working on MichMash, not sure if you sent that image over. If not, I'm sure I can download it from the old site.

**Comment by wdet30** [comment]
Great, thanks TB
________________________________
