### ISSUE TITLE
Post Page Missing Data

### ISSUE THREAD

**Issue by metastange** [arsmentis/wdet-conversion#92]
- [ ] Missing author byline
- [x] Missing publish date

**Comment by wdet30** [comment]
Is that on a single post or in blog view?



________________________________

**Comment by metastange** [comment]
All individual posts.

Example: https://wdetcms.wdet.org/2021/11/29/director-mike-mills-brings-detroit-students-to-big-screen-in-c-mon-c-mon/

**Comment by wdet30** [comment]
@artlogic, I'm not sure how to resolve this one. Please give a look if you can no rush.

**Comment by artlogic** [comment]
I don't see any indication that the news box pro theme actually displays bylines at the top of articles, opting for the display below the articles.

If a byline is needed it's going to take a filter or a customization. Let me know how to proceed.

**Comment by metastange** [comment]
I would like this included but am unclear who you're asking for direction from.

**Comment by artlogic** [comment]
Might be a good idea to have a quick meeting.

**Comment by artlogic** [comment]
Author bylines have been added.

**Comment by metastange** [comment]
Confirming I'm seeing this on my end. @wdet30, if we're able to style this at all, it would be great to add "by" to proceed the byline.
