### ISSUE TITLE
Author Widget Updates

### ISSUE THREAD

**Issue by metastange** [arsmentis/wdet-conversion#93]
- [ ] Not sure how much flexibility we have on the author widget that exists on post pages, but is it possible to only show a "short" description? For reference, compare Ryan's bios:

old site: https://wdet.org/posts/2021/11/29/91720-director-mike-mills-brings-detroit-students-to-big-screen-in-cmon-cmon/
new site: https://wdetcms.wdet.org/2021/11/29/director-mike-mills-brings-detroit-students-to-big-screen-in-c-mon-c-mon/

- [ ] Update button colors - background: 80C5D6 or 0C5C78, text: white

**Comment by artlogic** [comment]
A short bio is available to available to import. It looks like some configuration would need to be done for the authors plugin - this would be a change we would need to implement prior to Friday night - please let me know if we're going to do this (and if you want me to investigate)

**Comment by metastange** [comment]
If it's not going to put us behind, I'd like to move forward. Let me know if you need additional info from me.

**Comment by artlogic** [comment]
I think this ends up being @wdet30's call.

**Comment by wdet30** [comment]
@artlogic @metastange still looking into this. Not sure if I have any solutions.

**Comment by artlogic** [comment]
The solution I see involves adding custom fields to the author profile and them modifying the display templates. Let me know if this is something you want me to pursue.

**Comment by wdet30** [comment]
Please do what it takes to make it right.
________________________________

**Comment by artlogic** [comment]
After the import, the author boxed layout will need to be modified to use `short_bio` instead of `description|raw`.

**Comment by artlogic** [comment]
Tested - just need to update the importer.

**Comment by metastange** [comment]
To confirm - I won't be able to verify that until the next import, correct? Right now the boxes are blank, so just want to make sure.

**Comment by artlogic** [comment]
You can manually put short bios in for people right now to test. The next import will have the short bios populated with data.

**Comment by artlogic** [comment]
My work is done here - just awaiting verified post import.

**Comment by metastange** [comment]
There are currently two author bios populating on posts. There should one (the short bio version). Screenshot of issue:
![Screen Shot 2022-01-05 at 1 02 09 PM](https://user-images.githubusercontent.com/85897115/148266373-02bf3c65-955e-4732-a18f-f3e38bfcdd02.png)


Also, are we able to customize the formatting of these boxes? I would like them to look cleaner, have the same photo shapes, and be consistent with our brand colors.

**Comment by artlogic** [comment]
@metastange I believe you're handling the theme customization, but if I'm wrong please let me know.

You need to disable the second bio by unchecking "Show single post author bio?" in "Customizing ▸ Site blog settings Single Blog settings". This should be added to the customization notes (where they are being kept).

**Comment by artlogic** [comment]
You can change the template the author info on posts is made with by editing the boxed layout here: https://wdetcms.wdet.org/wp-admin/edit.php?post_type=ppmacf_layout

**Comment by metastange** [comment]
@artlogic ok, thanks.

@wdet30 please advise on how you want me to document my theme customization notes for posterity.

Also, I am not going to mess with the hard code in the template, @wdet30 can you please confirm if you are able change the color of the view all posts and email buttons and make the avatar a uniform shape? 

Finally, there's still a large gap between the author bio and "you may also like" portion; can this be cleaned up at all?

**Comment by wdet30** [comment]
I will check but may not have the answers till later today. Checking

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by wdet30** [comment]
@artlogic there are a few columns after the author widget. Do you know I can delete that space or clean things up for this issue? 

I'm not sure who to handle.

**Comment by wdet30** [comment]
It's not in the plugin. I turned it off and the issue was still there.

**Comment by artlogic** [comment]
The styles pushing things down (that you'd want to override) are the following:

```css
.post-footer-meta {
    margin: 40px 0 80px 0;
}

footer.entry-footer {
    display: block;
    margin: 50px 0 100px 0;
    width: 100%;
    overflow: hidden;
    min-height: 30px;
}

article.single-post {
    margin-bottom: 100px;
}
```

You might actually set the first to simply to not display because they don't seem to be populated.

**Comment by wdet30** [comment]
I can't fix it. I will get this in the next version.

**Comment by artlogic** [comment]
I don't believe I have any more work on this one - removing myself.

**Comment by wdet30** [comment]
Resolved
