### ISSUE TITLE
Something weird with authors 

### ISSUE THREAD

**Issue by wdet30** [arsmentis/wdet-conversion#94]
Hey @artlogic, look at the authors for cultureshift it has pulled in some weirdness. Please give a look. I'm not sure what's up here:
Author
https://wdetcms.wdet.org/author/cultureshift/

From post:
https://wdetcms.wdet.org/2021/11/24/this-week-at-the-detroit-film-theatre-the-macaluso-sisters/

**Comment by artlogic** [comment]
Looks pretty much identical to this: https://wdet.org/author/182/

**Comment by artlogic** [comment]
Unassigning myself on this one because I don't think this is an import issue, but a data issue with the old CMS.

**Comment by metastange** [comment]
Closing this since it is the same issue as #93.
