### ISSUE TITLE
Thumbnails on Pages

### ISSUE THREAD

**Issue by metastange** [arsmentis/wdet-conversion#95]
Thumbnail images are pulling into landing pages for some show and series landing pages. Let me know if you need a full list or if correcting the styling will correct all pages.

example:
https://wdetcms.wdet.org/series/artist-next-door-2/
https://wdetcms.wdet.org/shows/ann-delisis-essential-music/

**Comment by metastange** [comment]
FYI the thumbnails are still on the landing pages:
https://wdetcms.wdet.org/shows/ann-delisis-essential-music/

**Comment by wdet30** [comment]
Dang it, was working circling back. Will update soon.


________________________________

**Comment by wdet30** [comment]
@metastange, this has been resolved. 

https://wdetcms.wdet.org/shows/don-was-motor-city-playlist


and here : 

https://wdetcms.wdet.org/shows/ann-delisis-essential-music/
