### ISSUE TITLE
incorrect content included on show/series landing pages

### ISSUE THREAD

**Issue by metastange** [arsmentis/wdet-conversion#96]
There are non-shows/series listed on the shows/series landing pages. See below:
**Not Shows:**
- Auto Supplier Invests $66M, Creates 500+ Jobs in Plymouth
- Committee Approves Income Tax Rollback Despite Concerns About Unknown Repercussions
- Detroit’s Haven for Asylum Seekers Set to Lose Federal Funding
- GOP Strategist Ana Navarro: Time for Republicans to Launch Full Russia Investigation
- State Treasury Warns Against Telephone Tax Scams
- Take a Trial Run with the Paczki Coney Dog
- Warning for Small Pet Owners: Coyotes Coming

**Not Podcasts:**
- Detroit Today (technically is, but should not be included on this page)

**Not Series:**
- Do Trump’s Views on Manufacturing Jibe With Michigan CEOs?
- Gibby’s Grit Leads List of Great Detroit Tigers Moments
- SCOTUS Nominee Gorsuch and His Auto-Industry Related Rulings
- Snyder Announces Pilot Program to Improve Infrastructure

**Comment by wdet30** [comment]
I will give a look is it obvious or is it something I should be looking for?

________________________________

**Comment by metastange** [comment]
It's obvious. They are on the show landing page as though they are shows.

Example:
https://wdetcms.wdet.org/series/

**Comment by wdet30** [comment]
Okay this one I can fix not hard at all. The query tables are broken in elementor. And now I have a better system of backing those up I'll get those fixed tomorrow morning. And then I'll back up the query tables. So I want to leave this open. Thanks for the catch.
________________________________

**Comment by wdet30** [comment]
@metastange , changes have been made. Please let me know all everything's locks correct. I will create another backup of this update.

**Comment by metastange** [comment]
Looks good! Closing this ticket; checking this is on the transition timeline/checklist just to verify.
