### ISSUE TITLE
Sticky Posts - Plug In Needed

### ISSUE THREAD

**Issue by metastange** [arsmentis/wdet-conversion#97]
I played with the integrated sticky post function and I don't think it will serve our "featured post" needs as well as I would like; first of all, it seems to be adding posts to the modules when I make them sticky (so, for example, the 4 post module at the top includes 6 posts when i make two older posts sticky, messing with the layout of the homepage). In addition, the sticky posts then become the first featured posts in every active homepage module.

I poked around a little and it looks like there are plug-ins that would enable us to rank posts and select featured posts within categories. Please find something that can be implemented.

**Comment by wdet30** [comment]
@metastange, working on this. The last two plugins I tried didn't workout. I have four more to try.

**Comment by wdet30** [comment]
@metastange, i just installed a new plugin for you to try. Please give a look at the screenshot below to find the feature.
![stiky-1](https://user-images.githubusercontent.com/84190532/145878360-f1125dc1-019e-45b2-a318-c462da9c60f7.png)
