### ISSUE TITLE
Load testing

### ISSUE THREAD

**Issue by artlogic** [arsmentis/wdet-conversion#99]
The site should be load tested prior to launch at levels that we see for peak events.

**Comment by wdet30** [comment]
@artlogic, conversation with Marty on this issues is [here.](https://teams.microsoft.com/l/channel/19%3a43ea918d0a284b83920bac6a0e4523f8%40thread.tacv2/General?groupId=faa50dbf-02e8-4735-8ded-09a314fab678&tenantId=e51cdec9-811d-471d-bbe6-dd3d8d54c28b) 

I will update here as needed.

**Comment by wdet30** [comment]
.@artlogic my backup plan is to use loadster.

**Comment by artlogic** [comment]
Removing myself from this - it looks like I won't be involved.

**Comment by wdet30** [comment]
Your help is needed definitely. Not sure things came out right but we definitely need you.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by artlogic** [comment]
Let me know what you need from me.
